/**
 * Test Fixtures
 * Reusable test data for consistent testing
 */

import { Client, Service, Staff, LocalAppointment } from '../types';
import { TEST_SALON_ID } from './setup-db';

// Mock Clients
export const mockClients: Client[] = [
  {
    id: 'client-1',
    storeId: TEST_SALON_ID,
    name: 'John Doe',
    phone: '(555) 123-4567',
    email: 'john@example.com',
    notes: [],
    lastVisit: new Date('2024-01-15').toISOString(),
    totalVisits: 5,
    totalSpent: 250,
    createdAt: new Date('2023-06-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  } as any,
  {
    id: 'client-2',
    storeId: TEST_SALON_ID,
    name: 'Jane Smith',
    phone: '(555) 987-6543',
    email: 'jane@example.com',
    notes: [],
    lastVisit: new Date('2024-02-01').toISOString(),
    totalVisits: 12,
    totalSpent: 580,
    createdAt: new Date('2023-01-15').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  } as any,
  {
    id: 'client-3',
    storeId: TEST_SALON_ID,
    name: 'Bob Johnson',
    phone: '(555) 555-5555',
    email: 'bob@example.com',
    lastVisit: new Date('2024-01-20').toISOString(),
    totalVisits: 3,
    totalSpent: 120,
    createdAt: new Date('2023-11-01').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  } as any,
  {
    id: 'client-4',
    storeId: TEST_SALON_ID,
    name: 'Sarah Davis',
    phone: '(555) 111-2222',
    email: 'sarah@example.com',
    lastVisit: undefined, // New client
    totalVisits: 0,
    totalSpent: 0,
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
];

// Mock Services
export const mockServices: Service[] = [
  {
    id: 'service-1',
    storeId: TEST_SALON_ID,
    name: 'Haircut',
    category: 'Hair',
    duration: 30,
    price: 35,
    description: 'Professional haircut',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-2',
    storeId: TEST_SALON_ID,
    name: 'Hair Color',
    category: 'Hair',
    duration: 90,
    price: 85,
    description: 'Full hair coloring service',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-3',
    storeId: TEST_SALON_ID,
    name: 'Manicure',
    category: 'Nails',
    duration: 45,
    price: 25,
    description: 'Basic manicure service',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-4',
    storeId: TEST_SALON_ID,
    name: 'Pedicure',
    category: 'Nails',
    duration: 60,
    price: 35,
    description: 'Relaxing pedicure service',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-5',
    storeId: TEST_SALON_ID,
    name: 'Facial',
    category: 'Spa',
    duration: 60,
    price: 65,
    description: 'Rejuvenating facial treatment',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-6',
    storeId: TEST_SALON_ID,
    name: 'Massage',
    category: 'Spa',
    duration: 60,
    price: 80,
    description: 'Full body massage',
    commissionRate: 50,
    isActive: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'service-inactive',
    storeId: TEST_SALON_ID,
    name: 'Old Service',
    category: 'Deprecated',
    duration: 30,
    price: 20,
    description: 'This service is no longer offered',
    commissionRate: 50,
    isActive: false,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
];

// Mock Staff
export const mockStaff: Staff[] = [
  {
    id: 'staff-1',
    storeId: TEST_SALON_ID,
    name: 'Alice Smith',
    email: 'alice@salon.com',
    phone: '(555) 333-4444',
    role: 'Stylist',
    specialties: ['Hair'],
    specialty: 'Hair',
    isActive: true,
    status: 'available',
    schedule: [],
    servicesCountToday: 0,
    revenueToday: 0,
    tipsToday: 0,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'staff-2',
    storeId: TEST_SALON_ID,
    name: 'Bob Johnson',
    email: 'bob@salon.com',
    phone: '(555) 444-5555',
    role: 'Nail Technician',
    specialties: ['Nails'],
    specialty: 'Nails',
    isActive: true,
    status: 'available',
    schedule: [],
    servicesCountToday: 0,
    revenueToday: 0,
    tipsToday: 0,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'staff-3',
    storeId: TEST_SALON_ID,
    name: 'Carol Williams',
    email: 'carol@salon.com',
    phone: '(555) 666-7777',
    role: 'Spa Specialist',
    specialties: ['Spa'],
    specialty: 'Spa',
    isActive: true,
    status: 'available',
    schedule: [],
    servicesCountToday: 0,
    revenueToday: 0,
    tipsToday: 0,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: 'staff-4',
    storeId: TEST_SALON_ID,
    name: 'David Brown',
    email: 'david@salon.com',
    phone: '(555) 888-9999',
    role: 'Senior Stylist',
    specialties: ['Hair', 'Spa'],
    specialty: 'Hair',
    isActive: true,
    status: 'available',
    schedule: [],
    servicesCountToday: 0,
    revenueToday: 0,
    tipsToday: 0,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
  {
    id: '9999',
    storeId: TEST_SALON_ID,
    name: 'Next Available',
    email: '',
    phone: '',
    role: 'Auto Assign',
    specialties: [],
    isActive: true,
    status: 'available',
    schedule: [],
    servicesCountToday: 0,
    revenueToday: 0,
    tipsToday: 0,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-01').toISOString(),
    syncStatus: 'synced',
  },
];

// Mock Appointments
export const mockAppointments: LocalAppointment[] = [
  {
    id: 'apt-1',
    storeId: TEST_SALON_ID,
    clientId: 'client-1',
    clientName: 'John Doe',
    clientPhone: '(555) 123-4567',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T10:00:00').toISOString(),
    scheduledEndTime: new Date('2024-02-10T10:30:00').toISOString(),
    services: [{
      serviceId: mockServices[0].id,
      serviceName: mockServices[0].name,
      staffId: 'staff-1',
      staffName: 'Alice Smith',
      duration: mockServices[0].duration,
      price: mockServices[0].price,
    }], // Haircut
    status: 'scheduled',
    source: 'admin-portal',
    notes: 'Regular client',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
    syncStatus: 'synced',
    createdBy: 'user-1',
    lastModifiedBy: 'user-1',
  },
  {
    id: 'apt-2',
    storeId: TEST_SALON_ID,
    clientId: 'client-2',
    clientName: 'Jane Smith',
    clientPhone: '(555) 987-6543',
    staffId: 'staff-2',
    staffName: 'Bob Johnson',
    scheduledStartTime: new Date('2024-02-10T11:00:00').toISOString(),
    scheduledEndTime: new Date('2024-02-10T11:45:00').toISOString(),
    services: [{
      serviceId: mockServices[2].id,
      serviceName: mockServices[2].name,
      staffId: 'staff-2',
      staffName: 'Bob Johnson',
      duration: mockServices[2].duration,
      price: mockServices[2].price,
    }], // Manicure
    status: 'scheduled',
    source: 'online',
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
    syncStatus: 'synced',
    createdBy: 'user-1',
    lastModifiedBy: 'user-1',
  },
  {
    id: 'apt-3',
    storeId: TEST_SALON_ID,
    clientId: 'client-3',
    clientName: 'Bob Johnson',
    clientPhone: '(555) 555-5555',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T14:00:00').toISOString(),
    scheduledEndTime: new Date('2024-02-10T15:30:00').toISOString(),
    services: [{
      serviceId: mockServices[1].id,
      serviceName: mockServices[1].name,
      staffId: 'staff-1',
      staffName: 'Alice Smith',
      duration: mockServices[1].duration,
      price: mockServices[1].price,
    }], // Hair Color
    status: 'scheduled',
    source: 'walk-in',
    notes: 'First time coloring',
    createdAt: new Date('2024-02-09').toISOString(),
    updatedAt: new Date('2024-02-09').toISOString(),
    syncStatus: 'synced',
    createdBy: 'user-1',
    lastModifiedBy: 'user-1',
  },
  // Group booking appointments
  {
    id: 'apt-group-1',
    storeId: TEST_SALON_ID,
    clientId: 'client-1',
    clientName: 'John Doe',
    clientPhone: '(555) 123-4567',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T16:00:00').toISOString(),
    scheduledEndTime: new Date('2024-02-10T16:30:00').toISOString(),
    services: [{
      serviceId: mockServices[0].id,
      serviceName: mockServices[0].name,
      staffId: 'staff-1',
      staffName: 'Alice Smith',
      duration: mockServices[0].duration,
      price: mockServices[0].price,
    }], // Haircut
    status: 'scheduled',
    source: 'admin-portal',
    createdAt: new Date('2024-02-08').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
    syncStatus: 'synced',
    createdBy: 'user-1',
    lastModifiedBy: 'user-1',
  } as LocalAppointment,
  {
    id: 'apt-group-2',
    storeId: TEST_SALON_ID,
    clientId: 'client-2',
    clientName: 'Jane Smith',
    clientPhone: '(555) 987-6543',
    staffId: 'staff-2',
    staffName: 'Bob Johnson',
    scheduledStartTime: new Date('2024-02-10T16:00:00').toISOString(),
    scheduledEndTime: new Date('2024-02-10T16:45:00').toISOString(),
    services: [{
      serviceId: mockServices[2].id,
      serviceName: mockServices[2].name,
      staffId: 'staff-2',
      staffName: 'Bob Johnson',
      duration: mockServices[2].duration,
      price: mockServices[2].price,
    }], // Manicure
    status: 'scheduled',
    source: 'admin-portal',
    createdAt: new Date('2024-02-08').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
    syncStatus: 'synced',
    createdBy: 'user-1',
    lastModifiedBy: 'user-1',
  } as LocalAppointment,
];

// Default test date/time
export const TEST_DATE = new Date('2024-02-10T10:00:00');
export const TEST_TIME_SLOT = new Date('2024-02-10T14:00:00');