// Client Settings Constants - Sample data and design tokens

import type {
  EnhancedClient,
  LoyaltyTier,
  ClientSource,
  ClientGender,
  ClientTag,
} from './types';

// Design tokens for consistent styling
export const clientSettingsTokens = {
  colors: {
    primary: '#0891B2',
    primaryLight: '#06B6D4',
    primaryDark: '#0E7490',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
  },
  tierColors: {
    bronze: { bg: '#FEF3C7', text: '#92400E', border: '#D97706' },
    silver: { bg: '#F3F4F6', text: '#374151', border: '#9CA3AF' },
    gold: { bg: '#FEF9C3', text: '#854D0E', border: '#EAB308' },
    platinum: { bg: '#E0E7FF', text: '#3730A3', border: '#6366F1' },
    vip: { bg: '#FCE7F3', text: '#9D174D', border: '#EC4899' },
  },
  statusColors: {
    active: { bg: '#D1FAE5', text: '#065F46', dot: '#10B981' },
    blocked: { bg: '#FEE2E2', text: '#991B1B', dot: '#EF4444' },
    vip: { bg: '#FCE7F3', text: '#9D174D', dot: '#EC4899' },
  },
};

// Labels for display
export const tierLabels: Record<LoyaltyTier, string> = {
  bronze: 'Bronze',
  silver: 'Silver',
  gold: 'Gold',
  platinum: 'Platinum',
  vip: 'VIP',
};

export const sourceLabels: Record<ClientSource, string> = {
  walk_in: 'Walk-in',
  online_booking: 'Online Booking',
  referral: 'Referral',
  social_media: 'Social Media',
  google: 'Google',
  yelp: 'Yelp',
  instagram: 'Instagram',
  facebook: 'Facebook',
  tiktok: 'TikTok',
  advertisement: 'Advertisement',
  event: 'Event',
  gift_card: 'Gift Card',
  other: 'Other',
};

export const genderLabels: Record<ClientGender, string> = {
  female: 'Female',
  male: 'Male',
  non_binary: 'Non-binary',
  prefer_not_to_say: 'Prefer not to say',
};

// Default client tags
export const defaultTags: ClientTag[] = [
  { id: 'tag-vip', name: 'VIP', color: '#EC4899' },
  { id: 'tag-new', name: 'New Client', color: '#10B981' },
  { id: 'tag-regular', name: 'Regular', color: '#3B82F6' },
  { id: 'tag-color-client', name: 'Color Client', color: '#8B5CF6' },
  { id: 'tag-sensitive-scalp', name: 'Sensitive Scalp', color: '#F59E0B' },
  { id: 'tag-allergy-alert', name: 'Allergy Alert', color: '#EF4444' },
  { id: 'tag-wedding', name: 'Wedding Party', color: '#EC4899' },
  { id: 'tag-membership', name: 'Member', color: '#06B6D4' },
];

// Sample clients for development/testing
export const mockClients: EnhancedClient[] = [
  {
    id: 'client-1',
    salonId: 'salon-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    displayName: 'Sarah J.',
    avatar: undefined,
    gender: 'female',
    birthday: '1990-03-15',
    contact: {
      phone: '(555) 123-4567',
      phoneType: 'mobile',
      email: 'sarah.johnson@email.com',
      preferredContact: 'sms',
    },
    address: {
      street: '123 Main Street',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
    },
    source: 'referral',
    referredByClientName: 'Emily Davis',
    hairProfile: {
      type: 'wavy',
      texture: 'medium',
      density: 'thick',
      naturalColor: 'Dark Brown',
      currentColor: 'Caramel Balayage',
      colorFormulas: [
        {
          id: 'formula-1',
          date: '2024-10-15',
          formula: 'Redken Shades EQ 7GB + 8WG',
          brand: 'Redken',
          developer: '20 Vol',
          processingTime: '35 min',
          staffId: 'staff-1',
          staffName: 'Jessica Martinez',
        },
      ],
    },
    skinProfile: {
      type: 'combination',
      concerns: ['fine_lines', 'uneven_texture'],
    },
    medicalInfo: {
      allergies: ['PPD (hair dye)'],
      pregnancyStatus: 'not_applicable',
      consentFormSigned: true,
      consentFormDate: '2024-01-15',
    },
    preferences: {
      preferredStaffIds: ['staff-1'],
      preferredDays: [2, 4, 6], // Tue, Thu, Sat
      preferredTimes: 'afternoon',
      beveragePreference: 'Iced Latte',
      quietEnvironment: false,
    },
    communicationPreferences: {
      allowEmail: true,
      allowSms: true,
      allowPhone: false,
      allowMarketing: true,
      appointmentReminders: true,
      reminderTiming: 24,
      birthdayGreetings: true,
      promotionalOffers: true,
      newsletterSubscribed: true,
    },
    loyaltyInfo: {
      tier: 'gold',
      pointsBalance: 2450,
      lifetimePoints: 8500,
      memberSince: '2022-06-10',
      referralCode: 'SARAH2022',
      referralCount: 5,
      rewardsRedeemed: 3,
    },
    visitSummary: {
      totalVisits: 28,
      totalSpent: 4250.00,
      averageTicket: 151.78,
      lastVisitDate: '2024-11-15',
      favoriteService: 'Balayage',
      visitFrequency: 42,
      noShowCount: 0,
      lateCancelCount: 1,
      rebookRate: 95,
    },
    tags: [
      { id: 'tag-regular', name: 'Regular', color: '#3B82F6' },
      { id: 'tag-color-client', name: 'Color Client', color: '#8B5CF6' },
    ],
    notes: [
      {
        id: 'note-1',
        date: '2024-11-15',
        content: 'Client loves her new balayage! Wants to maintain this color going forward.',
        type: 'service',
        isPrivate: false,
        createdBy: 'staff-1',
        createdByName: 'Jessica Martinez',
      },
    ],
    isVip: false,
    isBlocked: false,
    createdAt: '2022-06-10T10:30:00Z',
    updatedAt: '2024-11-15T14:45:00Z',
    syncStatus: 'synced',
  },
  {
    id: 'client-2',
    salonId: 'salon-1',
    firstName: 'Michael',
    lastName: 'Chen',
    displayName: 'Mike C.',
    gender: 'male',
    birthday: '1985-08-22',
    contact: {
      phone: '(555) 234-5678',
      phoneType: 'mobile',
      email: 'mike.chen@email.com',
      preferredContact: 'email',
    },
    source: 'google',
    hairProfile: {
      type: 'straight',
      texture: 'coarse',
      density: 'thick',
      naturalColor: 'Black',
      currentColor: 'Black',
    },
    preferences: {
      preferredStaffIds: ['staff-2'],
      preferredDays: [6], // Saturday
      preferredTimes: 'morning',
      beveragePreference: 'Water',
    },
    communicationPreferences: {
      allowEmail: true,
      allowSms: false,
      allowPhone: false,
      allowMarketing: false,
      appointmentReminders: true,
      reminderTiming: 48,
      birthdayGreetings: false,
      promotionalOffers: false,
      newsletterSubscribed: false,
    },
    loyaltyInfo: {
      tier: 'silver',
      pointsBalance: 850,
      lifetimePoints: 2100,
      memberSince: '2023-03-20',
      referralCode: 'MIKE2023',
      referralCount: 1,
      rewardsRedeemed: 1,
    },
    visitSummary: {
      totalVisits: 14,
      totalSpent: 560.00,
      averageTicket: 40.00,
      lastVisitDate: '2024-11-02',
      favoriteService: "Men's Haircut",
      visitFrequency: 35,
      noShowCount: 0,
      lateCancelCount: 0,
      rebookRate: 100,
    },
    tags: [
      { id: 'tag-regular', name: 'Regular', color: '#3B82F6' },
    ],
    isVip: false,
    isBlocked: false,
    createdAt: '2023-03-20T09:15:00Z',
    updatedAt: '2024-11-02T10:30:00Z',
    syncStatus: 'synced',
  },
  {
    id: 'client-3',
    salonId: 'salon-1',
    firstName: 'Emily',
    lastName: 'Davis',
    displayName: 'Emily D.',
    gender: 'female',
    birthday: '1988-12-05',
    contact: {
      phone: '(555) 345-6789',
      phoneType: 'mobile',
      email: 'emily.davis@email.com',
      preferredContact: 'sms',
    },
    source: 'instagram',
    hairProfile: {
      type: 'curly',
      texture: 'fine',
      density: 'medium',
      porosity: 'high',
      naturalColor: 'Light Brown',
      currentColor: 'Platinum Blonde',
      colorFormulas: [
        {
          id: 'formula-2',
          date: '2024-09-20',
          formula: 'Wella Blondor + Olaplex No.1',
          brand: 'Wella',
          developer: '30 Vol',
          processingTime: '45 min',
          staffId: 'staff-1',
          staffName: 'Jessica Martinez',
        },
      ],
    },
    skinProfile: {
      type: 'sensitive',
      concerns: ['rosacea'],
      allergies: ['Fragrances'],
      sensitivities: ['Strong scents'],
    },
    medicalInfo: {
      allergies: ['Fragrances', 'Certain essential oils'],
      consentFormSigned: true,
      consentFormDate: '2023-01-10',
    },
    preferences: {
      preferredStaffIds: ['staff-1'],
      preferredDays: [3, 5], // Wed, Fri
      preferredTimes: 'afternoon',
      beveragePreference: 'Green Tea',
      quietEnvironment: true,
    },
    communicationPreferences: {
      allowEmail: true,
      allowSms: true,
      allowPhone: true,
      allowMarketing: true,
      appointmentReminders: true,
      reminderTiming: 24,
      birthdayGreetings: true,
      promotionalOffers: true,
      newsletterSubscribed: true,
    },
    loyaltyInfo: {
      tier: 'platinum',
      pointsBalance: 5200,
      lifetimePoints: 15000,
      memberSince: '2021-01-15',
      referralCode: 'EMILY2021',
      referralCount: 12,
      rewardsRedeemed: 8,
    },
    membership: {
      hasMembership: true,
      membershipType: 'Premium Color Club',
      membershipStartDate: '2024-01-01',
      autoRenew: true,
      monthlyCredits: 1,
      creditsRemaining: 1,
      membershipPrice: 199,
    },
    visitSummary: {
      totalVisits: 52,
      totalSpent: 8750.00,
      averageTicket: 168.27,
      lastVisitDate: '2024-11-20',
      favoriteService: 'Full Highlight',
      visitFrequency: 28,
      noShowCount: 0,
      lateCancelCount: 0,
      rebookRate: 100,
    },
    tags: [
      { id: 'tag-vip', name: 'VIP', color: '#EC4899' },
      { id: 'tag-color-client', name: 'Color Client', color: '#8B5CF6' },
      { id: 'tag-membership', name: 'Member', color: '#06B6D4' },
      { id: 'tag-sensitive-scalp', name: 'Sensitive Scalp', color: '#F59E0B' },
    ],
    notes: [
      {
        id: 'note-2',
        date: '2024-11-20',
        content: 'IMPORTANT: Use fragrance-free products only. Client has sensitivity to strong scents.',
        type: 'important',
        isPrivate: false,
        createdBy: 'staff-1',
        createdByName: 'Jessica Martinez',
      },
      {
        id: 'note-3',
        date: '2024-10-15',
        content: 'Loves the platinum look - wants to continue maintaining. Book 3 hours for full service.',
        type: 'service',
        isPrivate: false,
        createdBy: 'staff-1',
        createdByName: 'Jessica Martinez',
      },
    ],
    isVip: true,
    isBlocked: false,
    createdAt: '2021-01-15T11:00:00Z',
    updatedAt: '2024-11-20T16:30:00Z',
    syncStatus: 'synced',
  },
  {
    id: 'client-4',
    salonId: 'salon-1',
    firstName: 'Sophia',
    lastName: 'Martinez',
    displayName: 'Sophia M.',
    gender: 'female',
    birthday: '1995-05-28',
    contact: {
      phone: '(555) 456-7890',
      phoneType: 'mobile',
      email: 'sophia.martinez@email.com',
      preferredContact: 'app_notification',
    },
    source: 'online_booking',
    skinProfile: {
      type: 'oily',
      concerns: ['acne', 'large_pores'],
    },
    nailProfile: {
      condition: 'healthy',
      preferredShape: 'almond',
      preferredColors: ['Nude', 'French', 'Red'],
    },
    preferences: {
      preferredStaffIds: ['staff-3', 'staff-4'],
      preferredDays: [0, 6], // Sun, Sat
      preferredTimes: 'morning',
      beveragePreference: 'Sparkling Water',
      pressurePreference: 'medium',
    },
    communicationPreferences: {
      allowEmail: true,
      allowSms: true,
      allowPhone: false,
      allowMarketing: true,
      appointmentReminders: true,
      reminderTiming: 12,
      birthdayGreetings: true,
      promotionalOffers: true,
      newsletterSubscribed: false,
    },
    loyaltyInfo: {
      tier: 'gold',
      pointsBalance: 1850,
      lifetimePoints: 4200,
      memberSince: '2023-08-01',
      referralCode: 'SOPHIA2023',
      referralCount: 3,
      rewardsRedeemed: 2,
    },
    visitSummary: {
      totalVisits: 18,
      totalSpent: 1620.00,
      averageTicket: 90.00,
      lastVisitDate: '2024-11-18',
      favoriteService: 'Gel Manicure',
      visitFrequency: 14,
      noShowCount: 1,
      lateCancelCount: 2,
      rebookRate: 85,
    },
    tags: [
      { id: 'tag-regular', name: 'Regular', color: '#3B82F6' },
    ],
    isVip: false,
    isBlocked: false,
    createdAt: '2023-08-01T14:20:00Z',
    updatedAt: '2024-11-18T11:45:00Z',
    syncStatus: 'synced',
  },
  {
    id: 'client-5',
    salonId: 'salon-1',
    firstName: 'James',
    lastName: 'Wilson',
    displayName: 'James W.',
    gender: 'male',
    birthday: '1978-11-12',
    contact: {
      phone: '(555) 567-8901',
      phoneType: 'mobile',
      email: 'james.wilson@email.com',
      preferredContact: 'phone',
    },
    source: 'walk_in',
    preferences: {
      preferredStaffIds: ['staff-2'],
      preferredTimes: 'evening',
      beveragePreference: 'Coffee',
      pressurePreference: 'firm',
    },
    communicationPreferences: {
      allowEmail: false,
      allowSms: false,
      allowPhone: true,
      allowMarketing: false,
      appointmentReminders: true,
      reminderTiming: 24,
      birthdayGreetings: false,
      promotionalOffers: false,
      newsletterSubscribed: false,
    },
    loyaltyInfo: {
      tier: 'bronze',
      pointsBalance: 320,
      lifetimePoints: 320,
      memberSince: '2024-09-15',
      referralCode: 'JAMES2024',
      referralCount: 0,
      rewardsRedeemed: 0,
    },
    visitSummary: {
      totalVisits: 4,
      totalSpent: 320.00,
      averageTicket: 80.00,
      lastVisitDate: '2024-11-10',
      favoriteService: 'Massage - 60 min',
      visitFrequency: 21,
      noShowCount: 0,
      lateCancelCount: 0,
      rebookRate: 75,
    },
    tags: [
      { id: 'tag-new', name: 'New Client', color: '#10B981' },
    ],
    isVip: false,
    isBlocked: false,
    createdAt: '2024-09-15T17:30:00Z',
    updatedAt: '2024-11-10T18:15:00Z',
    syncStatus: 'synced',
  },
];

// Empty/default client for new client form
export const defaultClient: Partial<EnhancedClient> = {
  contact: {
    phone: '',
    phoneType: 'mobile',
    preferredContact: 'sms',
  },
  communicationPreferences: {
    allowEmail: true,
    allowSms: true,
    allowPhone: false,
    allowMarketing: false,
    appointmentReminders: true,
    reminderTiming: 24,
    birthdayGreetings: true,
    promotionalOffers: false,
    newsletterSubscribed: false,
  },
  loyaltyInfo: {
    tier: 'bronze',
    pointsBalance: 0,
    lifetimePoints: 0,
    referralCount: 0,
    rewardsRedeemed: 0,
  },
  visitSummary: {
    totalVisits: 0,
    totalSpent: 0,
    averageTicket: 0,
    noShowCount: 0,
    lateCancelCount: 0,
  },
  isVip: false,
  isBlocked: false,
};
