import { v4 as uuidv4 } from 'uuid';
import { db } from './schema';
import type { Staff, Client, Service } from '../types';

const SALON_ID = 'salon-001'; // Default salon ID for testing

export async function seedDatabase() {
  console.log('🌱 Seeding database...');

  // Clear existing data
  await db.staff.clear();
  await db.clients.clear();
  await db.services.clear();

  // Seed Staff - 20 staff members, all clocked in and ready
  const staffNames = [
    { name: 'Amy Chen', avatar: '👩‍🦰', specialty: 'hair' },
    { name: 'Beth Martinez', avatar: '👩‍🦱', specialty: 'nails' },
    { name: 'Carlos Rodriguez', avatar: '👨‍🦱', specialty: 'hair' },
    { name: 'Diana Kim', avatar: '👩', specialty: 'massage' },
    { name: 'Emma Wilson', avatar: '👩‍🦰', specialty: 'skincare' },
    { name: 'Frank Johnson', avatar: '👨', specialty: 'hair' },
    { name: 'Grace Lee', avatar: '👩‍🦳', specialty: 'nails' },
    { name: 'Henry Brown', avatar: '👨‍🦲', specialty: 'waxing' },
    { name: 'Isabella Garcia', avatar: '👩‍🦱', specialty: 'hair' },
    { name: 'James Taylor', avatar: '👨‍🦱', specialty: 'combo' },
    { name: 'Katherine Davis', avatar: '👩', specialty: 'nails' },
    { name: 'Liam Anderson', avatar: '👨', specialty: 'massage' },
    { name: 'Mia Thompson', avatar: '👩‍🦰', specialty: 'skincare' },
    { name: 'Noah White', avatar: '👨‍🦱', specialty: 'hair' },
    { name: 'Olivia Harris', avatar: '👩‍🦱', specialty: 'nails' },
    { name: 'Peter Clark', avatar: '👨', specialty: 'waxing' },
    { name: 'Quinn Lewis', avatar: '👩', specialty: 'combo' },
    { name: 'Rachel Walker', avatar: '👩‍🦰', specialty: 'skincare' },
    { name: 'Samuel Hall', avatar: '👨‍🦲', specialty: 'hair' },
    { name: 'Tina Young', avatar: '👩‍🦱', specialty: 'nails' },
  ];

  const clockInTime = new Date();
  clockInTime.setHours(9, 0, 0, 0); // All clocked in at 9 AM

  const staff: Staff[] = staffNames.map((staffInfo, index) => ({
    id: uuidv4(),
    salonId: SALON_ID,
    name: staffInfo.name,
    email: `${staffInfo.name.toLowerCase().replace(' ', '.')}@salon.com`,
    phone: `555-${String(1001 + index).padStart(4, '0')}`,
    avatar: staffInfo.avatar,
    specialties: [],
    status: 'available' as const, // All ready/available
    clockedInAt: clockInTime, // All clocked in
    schedule: [],
    servicesCountToday: Math.floor(Math.random() * 5), // 0-4 services
    revenueToday: Math.floor(Math.random() * 500), // 0-500 revenue
    tipsToday: Math.floor(Math.random() * 100), // 0-100 tips
    createdAt: new Date(),
    updatedAt: new Date(),
    syncStatus: 'synced' as const,
  }));

  // Update specialties - we'll need to match service IDs later if needed
  // For now, just set specialty field for StaffCard display
  staff.forEach((s, i) => {
    const specialtyType = staffNames[i].specialty;
    // This is for display purposes in StaffCard
    (s as any).specialty = specialtyType;
  });

  await db.staff.bulkAdd(staff);
  console.log(`✅ Seeded ${staff.length} staff members`);

  // Seed Clients
  const clients: Client[] = [
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Jane Doe',
      phone: '555-1001',
      email: 'jane@example.com',
      totalVisits: 5,
      totalSpent: 450,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'John Smith',
      phone: '555-1002',
      email: 'john@example.com',
      totalVisits: 3,
      totalSpent: 280,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Sarah Johnson',
      phone: '555-1003',
      email: 'sarah@example.com',
      totalVisits: 8,
      totalSpent: 720,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
  ];

  await db.clients.bulkAdd(clients);
  console.log(`✅ Seeded ${clients.length} clients`);

  // Seed Services - Complete Nail Salon Menu
  const services: Service[] = [
    // ====================
    // MANICURE SERVICES
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Basic Manicure',
      category: 'Manicure',
      description: 'Filing, shaping, cuticle care, buffing, and regular polish',
      duration: 30,
      price: 20,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Gel Manicure',
      category: 'Manicure',
      description: 'Premium gel polish with long-lasting shine (lasts 2-3 weeks)',
      duration: 45,
      price: 35,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'French Manicure',
      category: 'Manicure',
      description: 'Classic French tips with white and pink polish',
      duration: 40,
      price: 28,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Deluxe Spa Manicure',
      category: 'Manicure',
      description: 'Includes exfoliation, mask, hot towel treatment, and massage',
      duration: 60,
      price: 45,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Shellac Manicure',
      category: 'Manicure',
      description: 'Long-lasting shellac polish with high gloss finish',
      duration: 45,
      price: 40,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Paraffin Wax Manicure',
      category: 'Manicure',
      description: 'Therapeutic paraffin treatment with moisturizing benefits',
      duration: 50,
      price: 38,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // PEDICURE SERVICES
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Basic Pedicure',
      category: 'Pedicure',
      description: 'Soak, nail trimming, cuticle care, callus removal, and polish',
      duration: 45,
      price: 30,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Gel Pedicure',
      category: 'Pedicure',
      description: 'Premium gel polish pedicure with long-lasting results',
      duration: 60,
      price: 45,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'French Pedicure',
      category: 'Pedicure',
      description: 'Classic French tips on toes',
      duration: 50,
      price: 38,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Deluxe Spa Pedicure',
      category: 'Pedicure',
      description: 'Includes sugar scrub, mud mask, hot stone massage, and paraffin',
      duration: 75,
      price: 60,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Callus Treatment Pedicure',
      category: 'Pedicure',
      description: 'Intensive callus removal and foot smoothing treatment',
      duration: 60,
      price: 50,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Luxury Spa Pedicure',
      category: 'Pedicure',
      description: 'Ultimate pedicure with organic products and extended massage',
      duration: 90,
      price: 75,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // ARTIFICIAL NAILS
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Acrylic Full Set',
      category: 'Artificial Nails',
      description: 'Full set of acrylic nail extensions with shaping and polish',
      duration: 90,
      price: 55,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Acrylic Fill',
      category: 'Artificial Nails',
      description: 'Fill in grown-out acrylic nails with new acrylic',
      duration: 60,
      price: 35,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Gel Full Set',
      category: 'Artificial Nails',
      description: 'Hard gel nail extensions for a natural look',
      duration: 90,
      price: 65,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Gel Fill',
      category: 'Artificial Nails',
      description: 'Fill in grown-out gel extensions',
      duration: 60,
      price: 45,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Dip Powder Full Set',
      category: 'Artificial Nails',
      description: 'Long-lasting dip powder nails (SNS)',
      duration: 75,
      price: 50,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Dip Powder Fill',
      category: 'Artificial Nails',
      description: 'Fill in grown-out dip powder nails',
      duration: 60,
      price: 40,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Tips with Gel',
      category: 'Artificial Nails',
      description: 'Tip extensions with gel overlay',
      duration: 75,
      price: 55,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // NAIL ART & DESIGN
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Art - Simple Design',
      category: 'Nail Art',
      description: 'Basic nail art per nail (stripes, dots, simple patterns)',
      duration: 15,
      price: 5,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Art - Complex Design',
      category: 'Nail Art',
      description: 'Detailed nail art per nail (flowers, characters, intricate designs)',
      duration: 30,
      price: 10,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Ombre Nails',
      category: 'Nail Art',
      description: 'Beautiful gradient color blend on all nails',
      duration: 30,
      price: 15,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Chrome Nails',
      category: 'Nail Art',
      description: 'Mirror chrome powder finish',
      duration: 20,
      price: 15,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Rhinestones & Gems',
      category: 'Nail Art',
      description: '3D nail decorations with crystals and gems',
      duration: 20,
      price: 10,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Cat Eye Gel',
      category: 'Nail Art',
      description: 'Magnetic cat eye gel polish effect',
      duration: 15,
      price: 10,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // NAIL CARE & REPAIRS
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Repair',
      category: 'Nail Care',
      description: 'Fix broken or cracked natural or artificial nail',
      duration: 15,
      price: 10,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Gel Polish Removal',
      category: 'Nail Care',
      description: 'Safe removal of gel or shellac polish',
      duration: 20,
      price: 10,
      commissionRate: 40,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Acrylic Removal',
      category: 'Nail Care',
      description: 'Complete removal of acrylic nails',
      duration: 30,
      price: 15,
      commissionRate: 40,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Strengthening Treatment',
      category: 'Nail Care',
      description: 'Protein treatment for weak or damaged nails',
      duration: 20,
      price: 15,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Polish Change',
      category: 'Nail Care',
      description: 'Remove old polish and apply new color',
      duration: 20,
      price: 12,
      commissionRate: 45,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Cuticle Oil Treatment',
      category: 'Nail Care',
      description: 'Nourishing cuticle care and conditioning',
      duration: 10,
      price: 8,
      commissionRate: 45,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // SPECIALTY SERVICES
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Kids Manicure',
      category: 'Specialty',
      description: 'Age-appropriate nail service for children under 12',
      duration: 20,
      price: 15,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Kids Pedicure',
      category: 'Specialty',
      description: 'Gentle pedicure for children',
      duration: 30,
      price: 20,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Mens Manicure',
      category: 'Specialty',
      description: 'Grooming service focused on nail and cuticle care',
      duration: 30,
      price: 22,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Mens Pedicure',
      category: 'Specialty',
      description: 'Complete foot care and grooming service',
      duration: 45,
      price: 35,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },

    // ====================
    // ADD-ONS
    // ====================
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Nail Extension Per Nail',
      category: 'Add-Ons',
      description: 'Single nail extension replacement',
      duration: 10,
      price: 5,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Extra Length',
      category: 'Add-Ons',
      description: 'Additional charge for extra long nails',
      duration: 15,
      price: 10,
      commissionRate: 55,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Matte Top Coat',
      category: 'Add-Ons',
      description: 'Matte finish instead of glossy',
      duration: 5,
      price: 5,
      commissionRate: 60,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Hand Massage',
      category: 'Add-Ons',
      description: '10-minute relaxing hand and arm massage',
      duration: 10,
      price: 10,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
    {
      id: uuidv4(),
      salonId: SALON_ID,
      name: 'Foot Massage',
      category: 'Add-Ons',
      description: '15-minute relaxing foot and leg massage',
      duration: 15,
      price: 15,
      commissionRate: 50,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      syncStatus: 'synced',
    },
  ];

  await db.services.bulkAdd(services);
  console.log(`✅ Seeded ${services.length} services`);

  console.log('🎉 Database seeding complete!');
  return { staff, clients, services };
}

// Get salon ID for testing
export function getTestSalonId() {
  return SALON_ID;
}
