/**
 * Test Fixtures
 * Reusable test data for consistent testing
 */

import { Client, Service, Staff, LocalAppointment } from '../types';
import { TEST_SALON_ID } from './setup-db';

// Mock Clients
export const mockClients: Client[] = [
  {
    id: 'client-1',
    salonId: TEST_SALON_ID,
    name: 'John Doe',
    phone: '(555) 123-4567',
    email: 'john@example.com',
    notes: 'Prefers quiet corner',
    lastVisit: new Date('2024-01-15'),
    totalVisits: 5,
    totalSpent: 250,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'client-2',
    salonId: TEST_SALON_ID,
    name: 'Jane Smith',
    phone: '(555) 987-6543',
    email: 'jane@example.com',
    notes: 'Allergic to certain products',
    lastVisit: new Date('2024-02-01'),
    totalVisits: 12,
    totalSpent: 580,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'client-3',
    salonId: TEST_SALON_ID,
    name: 'Bob Johnson',
    phone: '(555) 555-5555',
    email: 'bob@example.com',
    lastVisit: new Date('2024-01-20'),
    totalVisits: 3,
    totalSpent: 120,
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'client-4',
    salonId: TEST_SALON_ID,
    name: 'Sarah Davis',
    phone: '(555) 111-2222',
    email: 'sarah@example.com',
    lastVisit: undefined, // New client
    totalVisits: 0,
    totalSpent: 0,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];

// Mock Services
export const mockServices: Service[] = [
  {
    id: 'service-1',
    salonId: TEST_SALON_ID,
    name: 'Haircut',
    category: 'Hair',
    duration: 30,
    price: 35,
    description: 'Professional haircut',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-2',
    salonId: TEST_SALON_ID,
    name: 'Hair Color',
    category: 'Hair',
    duration: 90,
    price: 85,
    description: 'Full hair coloring service',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-3',
    salonId: TEST_SALON_ID,
    name: 'Manicure',
    category: 'Nails',
    duration: 45,
    price: 25,
    description: 'Basic manicure service',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-4',
    salonId: TEST_SALON_ID,
    name: 'Pedicure',
    category: 'Nails',
    duration: 60,
    price: 35,
    description: 'Relaxing pedicure service',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-5',
    salonId: TEST_SALON_ID,
    name: 'Facial',
    category: 'Spa',
    duration: 60,
    price: 65,
    description: 'Rejuvenating facial treatment',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-6',
    salonId: TEST_SALON_ID,
    name: 'Massage',
    category: 'Spa',
    duration: 60,
    price: 80,
    description: 'Full body massage',
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'service-inactive',
    salonId: TEST_SALON_ID,
    name: 'Old Service',
    category: 'Deprecated',
    duration: 30,
    price: 20,
    description: 'This service is no longer offered',
    isActive: false,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

// Mock Staff
export const mockStaff: Staff[] = [
  {
    id: 'staff-1',
    salonId: TEST_SALON_ID,
    name: 'Alice Smith',
    email: 'alice@salon.com',
    phone: '(555) 333-4444',
    role: 'Stylist',
    specialties: ['Hair'],
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'staff-2',
    salonId: TEST_SALON_ID,
    name: 'Bob Johnson',
    email: 'bob@salon.com',
    phone: '(555) 444-5555',
    role: 'Nail Technician',
    specialties: ['Nails'],
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'staff-3',
    salonId: TEST_SALON_ID,
    name: 'Carol Williams',
    email: 'carol@salon.com',
    phone: '(555) 666-7777',
    role: 'Spa Specialist',
    specialties: ['Spa'],
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'staff-4',
    salonId: TEST_SALON_ID,
    name: 'David Brown',
    email: 'david@salon.com',
    phone: '(555) 888-9999',
    role: 'Senior Stylist',
    specialties: ['Hair', 'Spa'],
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '9999',
    salonId: TEST_SALON_ID,
    name: 'Next Available',
    email: '',
    phone: '',
    role: 'Auto Assign',
    specialties: [],
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

// Mock Appointments
export const mockAppointments: LocalAppointment[] = [
  {
    id: 'apt-1',
    salonId: TEST_SALON_ID,
    clientId: 'client-1',
    clientName: 'John Doe',
    clientPhone: '(555) 123-4567',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T10:00:00'),
    scheduledEndTime: new Date('2024-02-10T10:30:00'),
    services: [mockServices[0]], // Haircut
    status: 'scheduled',
    source: 'admin-portal',
    notes: 'Regular client',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'apt-2',
    salonId: TEST_SALON_ID,
    clientId: 'client-2',
    clientName: 'Jane Smith',
    clientPhone: '(555) 987-6543',
    staffId: 'staff-2',
    staffName: 'Bob Johnson',
    scheduledStartTime: new Date('2024-02-10T11:00:00'),
    scheduledEndTime: new Date('2024-02-10T11:45:00'),
    services: [mockServices[2]], // Manicure
    status: 'scheduled',
    source: 'online-booking',
    notes: '',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'apt-3',
    salonId: TEST_SALON_ID,
    clientId: 'client-3',
    clientName: 'Bob Johnson',
    clientPhone: '(555) 555-5555',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T14:00:00'),
    scheduledEndTime: new Date('2024-02-10T15:30:00'),
    services: [mockServices[1]], // Hair Color
    status: 'scheduled',
    source: 'walk-in',
    notes: 'First time coloring',
    createdAt: new Date('2024-02-09'),
    updatedAt: new Date('2024-02-09'),
  },
  // Group booking appointments
  {
    id: 'apt-group-1',
    salonId: TEST_SALON_ID,
    clientId: 'client-1',
    clientName: 'John Doe',
    clientPhone: '(555) 123-4567',
    staffId: 'staff-1',
    staffName: 'Alice Smith',
    scheduledStartTime: new Date('2024-02-10T16:00:00'),
    scheduledEndTime: new Date('2024-02-10T16:30:00'),
    services: [mockServices[0]], // Haircut
    status: 'scheduled',
    source: 'admin-portal',
    groupId: 'group-123',
    partySize: 3,
    namedClients: ['John Doe', 'Jane Smith', 'Bob Johnson'],
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
  {
    id: 'apt-group-2',
    salonId: TEST_SALON_ID,
    clientId: 'client-2',
    clientName: 'Jane Smith',
    clientPhone: '(555) 987-6543',
    staffId: 'staff-2',
    staffName: 'Bob Johnson',
    scheduledStartTime: new Date('2024-02-10T16:00:00'),
    scheduledEndTime: new Date('2024-02-10T16:45:00'),
    services: [mockServices[2]], // Manicure
    status: 'scheduled',
    source: 'admin-portal',
    groupId: 'group-123',
    partySize: 3,
    namedClients: ['John Doe', 'Jane Smith', 'Bob Johnson'],
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
];

// Default test date/time
export const TEST_DATE = new Date('2024-02-10T10:00:00');
export const TEST_TIME_SLOT = new Date('2024-02-10T14:00:00');