/**
 * ContactSection Component
 *
 * Renders the security credentials and notification preferences section:
 * - Security PIN (always required)
 * - Optional login account (password) setup
 * - Notification preferences
 */
import React from 'react';
import { Toggle } from '../../SharedComponents';
import type { LoginCredentials } from '../types';
import { generateRandomPIN, generateRandomPassword } from '../utils';

interface ContactSectionProps {
  loginCredentials: LoginCredentials;
  onCredentialsChange: (credentials: LoginCredentials) => void;
  errors: Record<string, string>;
  showPin: boolean;
  onShowPinChange: (show: boolean) => void;
  showPassword: boolean;
  onShowPasswordChange: (show: boolean) => void;
  email: string;
}

export const ContactSection: React.FC<ContactSectionProps> = ({
  loginCredentials,
  onCredentialsChange,
  errors,
  showPin,
  onShowPinChange,
  showPassword,
  onShowPasswordChange,
  email,
}) => {
  return (
    <div className="pt-4 border-t border-gray-200">
      {/* Security PIN Section - Always Required */}
      <div className="p-4 bg-gradient-to-br from-cyan-50 to-brand-50 border border-cyan-200 rounded-xl">
        <div className="flex items-start gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-cyan-100 flex items-center justify-center flex-shrink-0">
            <LockIcon className="w-5 h-5 text-cyan-600" />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-gray-900">Security PIN</h4>
            <p className="text-xs text-gray-600 mt-0.5">
              Required for all staff to access restricted features like reports, refunds, and settings.
            </p>
          </div>
        </div>

        {/* PIN Field - Always visible */}
        <div className="relative">
          <LockIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type={showPin ? 'text' : 'password'}
            value={loginCredentials.pin}
            onChange={(e) => {
              const val = e.target.value.replace(/\D/g, '').slice(0, 6);
              onCredentialsChange({ ...loginCredentials, pin: val, pinAutoGenerated: false });
            }}
            className={`w-full pl-10 pr-32 py-2.5 border rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition-all ${
              errors.pin ? 'border-red-300 bg-red-50' : 'border-gray-200'
            }`}
            placeholder="4-6 digit PIN"
          />
          <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
            <button
              type="button"
              onClick={() => onShowPinChange(!showPin)}
              className="p-1.5 text-gray-400 hover:text-gray-600 transition-colors"
              title={showPin ? 'Hide PIN' : 'Show PIN'}
            >
              {showPin ? <EyeOffIcon className="w-4 h-4" /> : <EyeIcon className="w-4 h-4" />}
            </button>
            <button
              type="button"
              onClick={() => onCredentialsChange({ ...loginCredentials, pin: generateRandomPIN(), pinAutoGenerated: true })}
              className="p-1.5 text-cyan-600 hover:text-cyan-700 transition-colors"
              title="Generate new PIN"
            >
              <RefreshIcon className="w-4 h-4" />
            </button>
          </div>
        </div>
        {errors.pin && (
          <p className="mt-1 text-sm text-red-500">{errors.pin}</p>
        )}
        {loginCredentials.pinAutoGenerated && (
          <p className="mt-2 text-xs text-cyan-700 flex items-center gap-1">
            <CheckIcon className="w-3 h-3" /> Auto-generated PIN
          </p>
        )}
      </div>

      {/* Optional: Login Account (Password) */}
      <div className="mt-4 p-4 bg-gray-50 rounded-xl">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h4 className="text-sm font-medium text-gray-900">Create Login Account</h4>
            <p className="text-xs text-gray-500 mt-0.5">
              Allow this member to sign in from any device
            </p>
          </div>
          <Toggle
            enabled={loginCredentials.enablePasswordLogin}
            onChange={(enabled) => {
              onCredentialsChange({
                ...loginCredentials,
                enablePasswordLogin: enabled,
                passwordSetupMethod: enabled ? 'manual' : 'none',
                password: enabled ? generateRandomPassword() : '',
              });
            }}
          />
        </div>

        {loginCredentials.enablePasswordLogin && (
          <div className="space-y-4 pt-4 border-t border-gray-200 animate-in fade-in duration-200">
            {/* Password Setup Method Selection */}
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => onCredentialsChange({
                  ...loginCredentials,
                  passwordSetupMethod: 'manual',
                  password: loginCredentials.password || generateRandomPassword(),
                })}
                className={`p-3 rounded-lg border-2 text-left transition-all ${
                  loginCredentials.passwordSetupMethod === 'manual'
                    ? 'border-cyan-500 bg-cyan-50'
                    : 'border-gray-200 hover:border-gray-300 bg-white'
                }`}
              >
                <div className="flex items-center gap-2">
                  <KeyIcon className={`w-4 h-4 ${
                    loginCredentials.passwordSetupMethod === 'manual' ? 'text-cyan-600' : 'text-gray-400'
                  }`} />
                  <span className={`text-sm font-medium ${
                    loginCredentials.passwordSetupMethod === 'manual' ? 'text-cyan-900' : 'text-gray-700'
                  }`}>
                    Set password now
                  </span>
                </div>
              </button>

              <button
                type="button"
                onClick={() => onCredentialsChange({
                  ...loginCredentials,
                  passwordSetupMethod: 'invite',
                  password: '',
                })}
                className={`p-3 rounded-lg border-2 text-left transition-all ${
                  loginCredentials.passwordSetupMethod === 'invite'
                    ? 'border-purple-500 bg-purple-50'
                    : 'border-gray-200 hover:border-gray-300 bg-white'
                }`}
              >
                <div className="flex items-center gap-2">
                  <SendIcon className={`w-4 h-4 ${
                    loginCredentials.passwordSetupMethod === 'invite' ? 'text-purple-600' : 'text-gray-400'
                  }`} />
                  <span className={`text-sm font-medium ${
                    loginCredentials.passwordSetupMethod === 'invite' ? 'text-purple-900' : 'text-gray-700'
                  }`}>
                    Send invite link
                  </span>
                </div>
              </button>
            </div>

            {/* Manual Password Field */}
            {loginCredentials.passwordSetupMethod === 'manual' && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">
                  Password
                </label>
                <div className="relative">
                  <KeyIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type={showPassword ? 'text' : 'password'}
                    value={loginCredentials.password}
                    onChange={(e) => onCredentialsChange({ ...loginCredentials, password: e.target.value })}
                    className={`w-full pl-10 pr-24 py-2.5 border rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition-all ${
                      errors.password ? 'border-red-300 bg-red-50' : 'border-gray-200'
                    }`}
                    placeholder="Enter password"
                  />
                  <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => onShowPasswordChange(!showPassword)}
                      className="p-1.5 text-gray-400 hover:text-gray-600 transition-colors"
                      title={showPassword ? 'Hide password' : 'Show password'}
                    >
                      {showPassword ? <EyeOffIcon className="w-4 h-4" /> : <EyeIcon className="w-4 h-4" />}
                    </button>
                    <button
                      type="button"
                      onClick={() => onCredentialsChange({ ...loginCredentials, password: generateRandomPassword() })}
                      className="p-1.5 text-cyan-600 hover:text-cyan-700 transition-colors"
                      title="Generate new password"
                    >
                      <RefreshIcon className="w-4 h-4" />
                    </button>
                  </div>
                </div>
                {errors.password && (
                  <p className="mt-1 text-sm text-red-500">{errors.password}</p>
                )}
              </div>
            )}

            {/* Invite Info */}
            {loginCredentials.passwordSetupMethod === 'invite' && (
              <div className="p-3 bg-purple-50 border border-purple-200 rounded-lg">
                <p className="text-xs text-purple-700">
                  An invite link will be generated for <strong>{email || '(enter email above)'}</strong> to set up their own password.
                </p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Notification Preference */}
      <div className="mt-4 p-4 bg-gray-50 rounded-xl">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h4 className="text-sm font-medium text-gray-900">Send Credentials</h4>
            <p className="text-xs text-gray-500 mt-0.5">
              Automatically notify member with their PIN{loginCredentials.enablePasswordLogin ? ' and password info' : ''}
            </p>
          </div>
          <Toggle
            enabled={loginCredentials.sendNotification}
            onChange={(enabled) => onCredentialsChange({ ...loginCredentials, sendNotification: enabled })}
          />
        </div>

        {loginCredentials.sendNotification && (
          <div className="flex gap-2 pt-3 border-t border-gray-200">
            {(['email', 'sms', 'both'] as const).map((method) => (
              <button
                key={method}
                type="button"
                onClick={() => onCredentialsChange({ ...loginCredentials, notificationMethod: method })}
                className={`flex-1 px-3 py-2 rounded-lg text-sm font-medium transition-all ${
                  loginCredentials.notificationMethod === method
                    ? 'bg-cyan-500 text-white'
                    : 'bg-white border border-gray-200 text-gray-700 hover:bg-gray-50'
                }`}
              >
                {method === 'email' ? 'Email' : method === 'sms' ? 'SMS' : 'Both'}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

// Icons
const LockIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
  </svg>
);

const EyeIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
  </svg>
);

const EyeOffIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
  </svg>
);

const RefreshIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
  </svg>
);

const CheckIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
  </svg>
);

const KeyIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
  </svg>
);

const SendIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
  </svg>
);

export default ContactSection;
