import React from 'react';
import type { WorkingDay, ServicePricing } from '../../../types';
import { dayNames } from '../../../constants';
import type { BasicInfo, LoginCredentials } from '../types';

interface RoleColor {
  bg: string;
  text: string;
  border: string;
}

interface ReviewSectionProps {
  basics: BasicInfo;
  loginCredentials: LoginCredentials;
  workingHours: WorkingDay[];
  services: ServicePricing[];
  getRoleColor: (roleId: string) => RoleColor;
  dynamicRoleLabels: Record<string, string>;
}

export const ReviewSection: React.FC<ReviewSectionProps> = ({
  basics,
  loginCredentials,
  workingHours,
  services,
  getRoleColor,
  dynamicRoleLabels,
}) => {
  const selectedServicesCount = services.filter(s => s.canPerform).length;
  const workingDaysCount = workingHours.filter(d => d.isWorking).length;

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
      <div className="bg-green-50 rounded-xl p-4">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center flex-shrink-0">
            <CheckCircleIcon className="w-5 h-5 text-green-600" />
          </div>
          <div>
            <h3 className="font-medium text-green-900">Almost Done!</h3>
            <p className="text-sm text-green-700 mt-0.5">
              Review the details below and click "Create Team Member" to finish.
            </p>
          </div>
        </div>
      </div>

      {/* Profile Card */}
      <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
        <div className="flex items-start gap-5">
          <div className="w-20 h-20 rounded-xl bg-gradient-to-br from-cyan-400 to-brand-500 flex items-center justify-center text-white text-2xl font-bold shadow-lg">
            {basics.firstName[0]}{basics.lastName[0]}
          </div>
          <div className="flex-1">
            <h3 className="text-xl font-semibold text-gray-900">
              {basics.firstName} {basics.lastName}
            </h3>
            <p className="text-gray-600 mt-0.5">
              {basics.title || dynamicRoleLabels[basics.role]}
            </p>
            <div className="mt-2">
              <span
                className="inline-flex px-3 py-1 rounded-full text-sm font-medium"
                style={{
                  backgroundColor: getRoleColor(basics.role).bg,
                  color: getRoleColor(basics.role).text,
                }}
              >
                {dynamicRoleLabels[basics.role]}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Details Grid */}
      <div className="grid grid-cols-2 gap-4">
        {/* Contact Info */}
        <div className="bg-gray-50 rounded-xl p-4">
          <h4 className="text-sm font-medium text-gray-500 mb-3">Contact Information</h4>
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-sm">
              <MailIcon className="w-4 h-4 text-gray-400" />
              <span className="text-gray-900">{basics.email}</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <PhoneIcon className="w-4 h-4 text-gray-400" />
              <span className="text-gray-900">{basics.phone}</span>
            </div>
          </div>
        </div>

        {/* Security Credentials */}
        <div className="bg-gray-50 rounded-xl p-4">
          <h4 className="text-sm font-medium text-gray-500 mb-3">Security Credentials</h4>
          <div className="space-y-2">
            {/* PIN - Always shown */}
            <div className="flex items-center gap-2 text-sm">
              <LockIcon className="w-4 h-4 text-cyan-500" />
              <span className="text-gray-700">PIN: {'•'.repeat(loginCredentials.pin.length)}</span>
              {loginCredentials.pinAutoGenerated && (
                <span className="text-xs text-cyan-600">(auto)</span>
              )}
            </div>

            {/* Password - if enabled */}
            {loginCredentials.enablePasswordLogin && loginCredentials.passwordSetupMethod === 'manual' && (
              <div className="flex items-center gap-2 text-sm">
                <KeyIcon className="w-4 h-4 text-green-500" />
                <span className="text-gray-700">Password: {loginCredentials.password.slice(0, 2)}{'•'.repeat(Math.max(0, loginCredentials.password.length - 2))}</span>
              </div>
            )}
            {loginCredentials.enablePasswordLogin && loginCredentials.passwordSetupMethod === 'invite' && (
              <div className="flex items-center gap-2 text-sm">
                <SendIcon className="w-4 h-4 text-purple-500" />
                <span className="text-purple-700">Invite link will be sent</span>
              </div>
            )}
            {!loginCredentials.enablePasswordLogin && (
              <div className="flex items-center gap-2 text-sm">
                <KeyIcon className="w-4 h-4 text-gray-400" />
                <span className="text-gray-500">No login account</span>
              </div>
            )}

            {/* Notification */}
            {loginCredentials.sendNotification && (
              <div className="flex items-center gap-2 text-sm mt-2 pt-2 border-t border-gray-200">
                <MailIcon className="w-4 h-4 text-blue-500" />
                <span className="text-gray-600">
                  Will notify via {loginCredentials.notificationMethod === 'both' ? 'email & SMS' : loginCredentials.notificationMethod}
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Schedule Summary */}
        <div className="bg-gray-50 rounded-xl p-4">
          <h4 className="text-sm font-medium text-gray-500 mb-3">Schedule</h4>
          <div className="space-y-1">
            <p className="text-sm text-gray-900 font-medium">
              {workingDaysCount} days per week
            </p>
            <p className="text-xs text-gray-500">
              {workingHours
                .filter(d => d.isWorking)
                .map(d => dayNames[d.dayOfWeek].slice(0, 3))
                .join(', ')
              }
            </p>
          </div>
        </div>

        {/* Services Summary */}
        <div className="bg-gray-50 rounded-xl p-4 col-span-2">
          <h4 className="text-sm font-medium text-gray-500 mb-3">Assigned Services</h4>
          {selectedServicesCount > 0 ? (
            <div className="flex flex-wrap gap-2">
              {services
                .filter(s => s.canPerform)
                .slice(0, 8)
                .map(s => (
                  <span
                    key={s.serviceId}
                    className="px-2.5 py-1 bg-white border border-gray-200 rounded-lg text-sm text-gray-700"
                  >
                    {s.serviceName}
                  </span>
                ))
              }
              {selectedServicesCount > 8 && (
                <span className="px-2.5 py-1 bg-cyan-50 text-cyan-700 rounded-lg text-sm font-medium">
                  +{selectedServicesCount - 8} more
                </span>
              )}
            </div>
          ) : (
            <p className="text-sm text-gray-500">No services assigned yet</p>
          )}
        </div>
      </div>

      {/* Bio */}
      {basics.bio && (
        <div className="bg-gray-50 rounded-xl p-4">
          <h4 className="text-sm font-medium text-gray-500 mb-2">Bio</h4>
          <p className="text-sm text-gray-700">{basics.bio}</p>
        </div>
      )}
    </div>
  );
};

// Icons
const CheckCircleIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
);

const MailIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
  </svg>
);

const PhoneIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
  </svg>
);

const LockIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
  </svg>
);

const KeyIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
  </svg>
);

const SendIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
  </svg>
);

export default ReviewSection;
