import type {
  TeamMemberSettings,
  TeamSettingsUIState,
  StaffRole,
  Permission,
  WorkingDay,
  ServicePricing,
} from './types';

// Design Tokens for Team Settings
export const teamSettingsTokens = {
  colors: {
    primary: '#00BCD4',
    primaryLight: '#E0F7FA',
    primaryDark: '#0097A7',
    accent: '#FF6B9D',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  roleColors: {
    owner: { bg: '#E8EAF6', text: '#3949AB', border: '#7986CB' },
    manager: { bg: '#E3F2FD', text: '#1976D2', border: '#64B5F6' },
    senior_stylist: { bg: '#E0F2F1', text: '#00897B', border: '#4DB6AC' },
    stylist: { bg: '#E8F5E9', text: '#388E3C', border: '#81C784' },
    junior_stylist: { bg: '#F1F8E9', text: '#558B2F', border: '#AED581' },
    apprentice: { bg: '#FFF3E0', text: '#EF6C00', border: '#FFB74D' },
    receptionist: { bg: '#F3E5F5', text: '#7B1FA2', border: '#BA68C8' },
    assistant: { bg: '#ECEFF1', text: '#546E7A', border: '#90A4AE' },
    nail_technician: { bg: '#FCE4EC', text: '#C2185B', border: '#F06292' },
    esthetician: { bg: '#FFF8E1', text: '#FF8F00', border: '#FFD54F' },
    massage_therapist: { bg: '#E0F7FA', text: '#00838F', border: '#4DD0E1' },
    barber: { bg: '#EFEBE9', text: '#5D4037', border: '#A1887F' },
    colorist: { bg: '#EDE7F6', text: '#512DA8', border: '#9575CD' },
    makeup_artist: { bg: '#FFEBEE', text: '#C62828', border: '#EF9A9A' },
  },
  statusColors: {
    active: { bg: '#E8F5E9', text: '#2E7D32', dot: '#66BB6A' },
    inactive: { bg: '#FFEBEE', text: '#C62828', dot: '#EF5350' },
    onLeave: { bg: '#FFF3E0', text: '#EF6C00', dot: '#FFA726' },
  },
};

export const roleLabels: Record<StaffRole, string> = {
  owner: 'Owner',
  manager: 'Manager',
  senior_stylist: 'Senior Stylist',
  stylist: 'Stylist',
  junior_stylist: 'Junior Stylist',
  apprentice: 'Apprentice',
  receptionist: 'Receptionist',
  assistant: 'Assistant',
  nail_technician: 'Nail Technician',
  esthetician: 'Esthetician',
  massage_therapist: 'Massage Therapist',
  barber: 'Barber',
  colorist: 'Colorist',
  makeup_artist: 'Makeup Artist',
};

export const defaultWorkingHours: WorkingDay[] = [
  { dayOfWeek: 0, isWorking: false, shifts: [] }, // Sunday
  { dayOfWeek: 1, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
  { dayOfWeek: 2, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
  { dayOfWeek: 3, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
  { dayOfWeek: 4, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
  { dayOfWeek: 5, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
  { dayOfWeek: 6, isWorking: false, shifts: [] }, // Saturday
];

export const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export const dayNamesShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export const defaultPermissions: Permission[] = [
  { id: 'view_calendar', name: 'View Calendar', description: 'View appointment calendar', category: 'appointments', level: 'full' },
  { id: 'create_appointments', name: 'Create Appointments', description: 'Create new appointments', category: 'appointments', level: 'full' },
  { id: 'edit_appointments', name: 'Edit Appointments', description: 'Modify existing appointments', category: 'appointments', level: 'full' },
  { id: 'delete_appointments', name: 'Delete Appointments', description: 'Remove appointments', category: 'appointments', level: 'limited' },
  { id: 'view_clients', name: 'View Clients', description: 'Access client information', category: 'clients', level: 'full' },
  { id: 'create_clients', name: 'Create Clients', description: 'Add new clients', category: 'clients', level: 'full' },
  { id: 'edit_clients', name: 'Edit Clients', description: 'Modify client data', category: 'clients', level: 'full' },
  { id: 'view_client_history', name: 'View Client History', description: 'Access client service history', category: 'clients', level: 'full' },
  { id: 'process_payments', name: 'Process Payments', description: 'Handle payment transactions', category: 'sales', level: 'full' },
  { id: 'apply_discounts', name: 'Apply Discounts', description: 'Apply discounts to services', category: 'sales', level: 'limited' },
  { id: 'process_refunds', name: 'Process Refunds', description: 'Issue refunds', category: 'sales', level: 'none' },
  { id: 'view_reports', name: 'View Reports', description: 'Access business reports', category: 'reports', level: 'view_only' },
  { id: 'export_reports', name: 'Export Reports', description: 'Download report data', category: 'reports', level: 'none' },
  { id: 'view_team', name: 'View Team', description: 'See team member info', category: 'team', level: 'full' },
  { id: 'manage_team', name: 'Manage Team', description: 'Add/edit team members', category: 'team', level: 'none' },
  { id: 'access_settings', name: 'Access Settings', description: 'View system settings', category: 'settings', level: 'view_only' },
  { id: 'modify_settings', name: 'Modify Settings', description: 'Change system settings', category: 'settings', level: 'none' },
];

export const defaultUIState: TeamSettingsUIState = {
  selectedMemberId: null,
  activeSection: 'profile',
  searchQuery: '',
  filterRole: 'all',
  filterStatus: 'all',
  sortBy: 'name',
  sortOrder: 'asc',
  isAddingNew: false,
  hasUnsavedChanges: false,
};

// Mock service categories for the UI
export const serviceCategories = [
  { id: 'hair', name: 'Hair Services', icon: 'scissors' },
  { id: 'nails', name: 'Nail Services', icon: 'hand' },
  { id: 'skin', name: 'Skin Care', icon: 'sparkles' },
  { id: 'massage', name: 'Massage & Body', icon: 'heart' },
  { id: 'makeup', name: 'Makeup', icon: 'palette' },
  { id: 'waxing', name: 'Waxing', icon: 'zap' },
  { id: 'men', name: "Men's Grooming", icon: 'user' },
];

// Mock services for the UI
export const mockServices: ServicePricing[] = [
  { serviceId: 's1', serviceName: 'Women\'s Haircut', serviceCategory: 'hair', canPerform: true, defaultPrice: 65, defaultDuration: 45 },
  { serviceId: 's2', serviceName: 'Men\'s Haircut', serviceCategory: 'hair', canPerform: true, defaultPrice: 35, defaultDuration: 30 },
  { serviceId: 's3', serviceName: 'Blowout', serviceCategory: 'hair', canPerform: true, defaultPrice: 45, defaultDuration: 30 },
  { serviceId: 's4', serviceName: 'Full Color', serviceCategory: 'hair', canPerform: false, defaultPrice: 120, defaultDuration: 90 },
  { serviceId: 's5', serviceName: 'Highlights', serviceCategory: 'hair', canPerform: false, defaultPrice: 150, defaultDuration: 120 },
  { serviceId: 's6', serviceName: 'Balayage', serviceCategory: 'hair', canPerform: false, defaultPrice: 200, defaultDuration: 150 },
  { serviceId: 's7', serviceName: 'Deep Conditioning', serviceCategory: 'hair', canPerform: true, defaultPrice: 35, defaultDuration: 20 },
  { serviceId: 's8', serviceName: 'Classic Manicure', serviceCategory: 'nails', canPerform: false, defaultPrice: 30, defaultDuration: 30 },
  { serviceId: 's9', serviceName: 'Gel Manicure', serviceCategory: 'nails', canPerform: false, defaultPrice: 45, defaultDuration: 45 },
  { serviceId: 's10', serviceName: 'Classic Pedicure', serviceCategory: 'nails', canPerform: false, defaultPrice: 45, defaultDuration: 45 },
  { serviceId: 's11', serviceName: 'Facial - Classic', serviceCategory: 'skin', canPerform: false, defaultPrice: 85, defaultDuration: 60 },
  { serviceId: 's12', serviceName: 'Facial - Hydrating', serviceCategory: 'skin', canPerform: false, defaultPrice: 95, defaultDuration: 60 },
  { serviceId: 's13', serviceName: 'Swedish Massage', serviceCategory: 'massage', canPerform: false, defaultPrice: 90, defaultDuration: 60 },
  { serviceId: 's14', serviceName: 'Deep Tissue Massage', serviceCategory: 'massage', canPerform: false, defaultPrice: 110, defaultDuration: 60 },
  { serviceId: 's15', serviceName: 'Full Face Wax', serviceCategory: 'waxing', canPerform: false, defaultPrice: 45, defaultDuration: 30 },
  { serviceId: 's16', serviceName: 'Brow Wax', serviceCategory: 'waxing', canPerform: false, defaultPrice: 18, defaultDuration: 15 },
  { serviceId: 's17', serviceName: 'Bridal Makeup', serviceCategory: 'makeup', canPerform: false, defaultPrice: 150, defaultDuration: 90 },
  { serviceId: 's18', serviceName: 'Event Makeup', serviceCategory: 'makeup', canPerform: false, defaultPrice: 85, defaultDuration: 60 },
];

// Default sync fields for mock data
const defaultSyncFields = {
  tenantId: 'default-tenant',
  storeId: 'default-store',
  syncStatus: 'synced' as const,
  version: 1,
  vectorClock: { seed: 1 },
  lastSyncedVersion: 1,
  createdBy: 'seed',
  createdByDevice: 'seed',
  lastModifiedBy: 'seed',
  lastModifiedByDevice: 'seed',
  isDeleted: false,
};

// Mock team members for the UI
export const mockTeamMembers: TeamMemberSettings[] = [
  {
    id: 'tm1',
    ...defaultSyncFields,
    profile: {
      id: 'tm1',
      firstName: 'Sarah',
      lastName: 'Mitchell',
      displayName: 'Sarah M.',
      email: 'sarah@mangosalon.com',
      phone: '(555) 123-4567',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      bio: 'Senior stylist with 10+ years of experience specializing in color correction and balayage.',
      title: 'Senior Stylist & Colorist',
      hireDate: '2019-03-15',
    },
    services: mockServices.map((s, i) => ({ ...s, canPerform: i < 7 })),
    workingHours: {
      regularHours: defaultWorkingHours,
      timeOffRequests: [],
      scheduleOverrides: [],
      defaultBreakDuration: 30,
      autoScheduleBreaks: true,
    },
    permissions: {
      role: 'senior_stylist',
      permissions: defaultPermissions,
      canAccessAdminPortal: false,
      canAccessReports: true,
      canModifyPrices: false,
      canProcessRefunds: false,
      canDeleteRecords: false,
      canManageTeam: false,
      canViewOthersCalendar: true,
      canBookForOthers: true,
      canEditOthersAppointments: false,
      pinRequired: true,
      pin: '1234',
    },
    commission: {
      type: 'percentage',
      basePercentage: 45,
      productCommission: 10,
      tipHandling: 'keep_all',
    },
    payroll: {
      payPeriod: 'bi-weekly',
      guaranteedMinimum: 800,
    },
    onlineBooking: {
      isBookableOnline: true,
      showOnWebsite: true,
      showOnApp: true,
      maxAdvanceBookingDays: 60,
      minAdvanceBookingHours: 2,
      bufferBetweenAppointments: 15,
      bufferType: 'after',
      allowDoubleBooking: false,
      maxConcurrentAppointments: 1,
      requireDeposit: false,
      autoAcceptBookings: true,
      acceptNewClients: true,
      displayOrder: 1,
      specialties: ['Color Correction', 'Balayage', 'Highlights'],
    },
    notifications: {
      email: {
        appointmentReminders: true,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        dailySummary: true,
        weeklySummary: false,
        marketingEmails: false,
        systemUpdates: true,
      },
      sms: {
        appointmentReminders: false,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        urgentAlerts: true,
      },
      push: {
        appointmentReminders: true,
        newBookings: true,
        messages: true,
        teamUpdates: false,
      },
      reminderTiming: {
        firstReminder: 24,
        secondReminder: 2,
      },
    },
    performanceGoals: {
      dailyRevenueTarget: 800,
      weeklyRevenueTarget: 4000,
      monthlyRevenueTarget: 16000,
      rebookingRateTarget: 75,
    },
    isActive: true,
    createdAt: '2019-03-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'tm2',
    ...defaultSyncFields,
    profile: {
      id: 'tm2',
      firstName: 'Marcus',
      lastName: 'Johnson',
      displayName: 'Marcus J.',
      email: 'marcus@mangosalon.com',
      phone: '(555) 234-5678',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      bio: 'Master barber specializing in fades, beard grooming, and classic cuts.',
      title: 'Master Barber',
      hireDate: '2020-06-01',
    },
    services: mockServices.map((s) => ({ ...s, canPerform: ['s1', 's2', 's3'].includes(s.serviceId) })),
    workingHours: {
      regularHours: [
        { dayOfWeek: 0, isWorking: false, shifts: [] },
        { dayOfWeek: 1, isWorking: true, shifts: [{ startTime: '10:00', endTime: '19:00' }] },
        { dayOfWeek: 2, isWorking: true, shifts: [{ startTime: '10:00', endTime: '19:00' }] },
        { dayOfWeek: 3, isWorking: false, shifts: [] },
        { dayOfWeek: 4, isWorking: true, shifts: [{ startTime: '10:00', endTime: '19:00' }] },
        { dayOfWeek: 5, isWorking: true, shifts: [{ startTime: '10:00', endTime: '19:00' }] },
        { dayOfWeek: 6, isWorking: true, shifts: [{ startTime: '09:00', endTime: '17:00' }] },
      ],
      timeOffRequests: [],
      scheduleOverrides: [],
      defaultBreakDuration: 30,
      autoScheduleBreaks: true,
    },
    permissions: {
      role: 'barber',
      permissions: defaultPermissions,
      canAccessAdminPortal: false,
      canAccessReports: false,
      canModifyPrices: false,
      canProcessRefunds: false,
      canDeleteRecords: false,
      canManageTeam: false,
      canViewOthersCalendar: true,
      canBookForOthers: false,
      canEditOthersAppointments: false,
      pinRequired: true,
    },
    commission: {
      type: 'percentage',
      basePercentage: 50,
      productCommission: 15,
      tipHandling: 'keep_all',
    },
    payroll: {
      payPeriod: 'weekly',
    },
    onlineBooking: {
      isBookableOnline: true,
      showOnWebsite: true,
      showOnApp: true,
      maxAdvanceBookingDays: 30,
      minAdvanceBookingHours: 1,
      bufferBetweenAppointments: 10,
      bufferType: 'after',
      allowDoubleBooking: false,
      maxConcurrentAppointments: 1,
      requireDeposit: false,
      autoAcceptBookings: true,
      acceptNewClients: true,
      displayOrder: 2,
      specialties: ['Fades', 'Beard Grooming', 'Classic Cuts'],
    },
    notifications: {
      email: {
        appointmentReminders: false,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        dailySummary: false,
        weeklySummary: false,
        marketingEmails: false,
        systemUpdates: false,
      },
      sms: {
        appointmentReminders: true,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        urgentAlerts: true,
      },
      push: {
        appointmentReminders: true,
        newBookings: true,
        messages: true,
        teamUpdates: true,
      },
      reminderTiming: {
        firstReminder: 24,
      },
    },
    performanceGoals: {
      dailyRevenueTarget: 600,
      weeklyRevenueTarget: 3000,
    },
    isActive: true,
    createdAt: '2020-06-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'tm3',
    ...defaultSyncFields,
    profile: {
      id: 'tm3',
      firstName: 'Emily',
      lastName: 'Chen',
      displayName: 'Emily C.',
      email: 'emily@mangosalon.com',
      phone: '(555) 345-6789',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      bio: 'Licensed esthetician with expertise in advanced skincare treatments and facials.',
      title: 'Lead Esthetician',
      hireDate: '2021-02-10',
    },
    services: mockServices.map((s) => ({ ...s, canPerform: ['s11', 's12', 's15', 's16'].includes(s.serviceId) })),
    workingHours: {
      regularHours: defaultWorkingHours,
      timeOffRequests: [],
      scheduleOverrides: [],
      defaultBreakDuration: 45,
      autoScheduleBreaks: true,
    },
    permissions: {
      role: 'esthetician',
      permissions: defaultPermissions,
      canAccessAdminPortal: false,
      canAccessReports: true,
      canModifyPrices: false,
      canProcessRefunds: false,
      canDeleteRecords: false,
      canManageTeam: false,
      canViewOthersCalendar: true,
      canBookForOthers: true,
      canEditOthersAppointments: false,
      pinRequired: true,
    },
    commission: {
      type: 'tiered',
      basePercentage: 40,
      tiers: [
        { minRevenue: 0, maxRevenue: 5000, percentage: 40 },
        { minRevenue: 5000, maxRevenue: 10000, percentage: 45 },
        { minRevenue: 10000, percentage: 50 },
      ],
      productCommission: 20,
      tipHandling: 'keep_all',
      retailCommission: 15,
    },
    payroll: {
      payPeriod: 'bi-weekly',
    },
    onlineBooking: {
      isBookableOnline: true,
      showOnWebsite: true,
      showOnApp: true,
      maxAdvanceBookingDays: 45,
      minAdvanceBookingHours: 4,
      bufferBetweenAppointments: 15,
      bufferType: 'both',
      allowDoubleBooking: false,
      maxConcurrentAppointments: 1,
      requireDeposit: true,
      depositAmount: 25,
      autoAcceptBookings: true,
      acceptNewClients: true,
      displayOrder: 3,
      specialties: ['Advanced Facials', 'Chemical Peels', 'Microdermabrasion'],
    },
    notifications: {
      email: {
        appointmentReminders: true,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        dailySummary: true,
        weeklySummary: true,
        marketingEmails: true,
        systemUpdates: true,
      },
      sms: {
        appointmentReminders: false,
        appointmentChanges: false,
        newBookings: false,
        cancellations: false,
        urgentAlerts: true,
      },
      push: {
        appointmentReminders: true,
        newBookings: true,
        messages: true,
        teamUpdates: true,
      },
      reminderTiming: {
        firstReminder: 48,
        secondReminder: 4,
      },
    },
    performanceGoals: {
      dailyRevenueTarget: 700,
      weeklyRevenueTarget: 3500,
      monthlyRevenueTarget: 14000,
      rebookingRateTarget: 80,
      retailSalesTarget: 500,
    },
    isActive: true,
    createdAt: '2021-02-10T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'tm4',
    ...defaultSyncFields,
    profile: {
      id: 'tm4',
      firstName: 'Jessica',
      lastName: 'Williams',
      displayName: 'Jessica W.',
      email: 'jessica@mangosalon.com',
      phone: '(555) 456-7890',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
      bio: 'Nail artist with a passion for creative designs and nail art.',
      title: 'Nail Technician',
      hireDate: '2022-08-20',
    },
    services: mockServices.map((s) => ({ ...s, canPerform: ['s8', 's9', 's10'].includes(s.serviceId) })),
    workingHours: {
      regularHours: [
        { dayOfWeek: 0, isWorking: true, shifts: [{ startTime: '10:00', endTime: '16:00' }] },
        { dayOfWeek: 1, isWorking: false, shifts: [] },
        { dayOfWeek: 2, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
        { dayOfWeek: 3, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
        { dayOfWeek: 4, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
        { dayOfWeek: 5, isWorking: true, shifts: [{ startTime: '09:00', endTime: '18:00' }] },
        { dayOfWeek: 6, isWorking: true, shifts: [{ startTime: '09:00', endTime: '17:00' }] },
      ],
      timeOffRequests: [],
      scheduleOverrides: [],
      defaultBreakDuration: 30,
      autoScheduleBreaks: true,
    },
    permissions: {
      role: 'nail_technician',
      permissions: defaultPermissions,
      canAccessAdminPortal: false,
      canAccessReports: false,
      canModifyPrices: false,
      canProcessRefunds: false,
      canDeleteRecords: false,
      canManageTeam: false,
      canViewOthersCalendar: false,
      canBookForOthers: false,
      canEditOthersAppointments: false,
      pinRequired: true,
    },
    commission: {
      type: 'percentage',
      basePercentage: 45,
      productCommission: 10,
      tipHandling: 'keep_all',
    },
    payroll: {
      payPeriod: 'weekly',
    },
    onlineBooking: {
      isBookableOnline: true,
      showOnWebsite: true,
      showOnApp: true,
      maxAdvanceBookingDays: 30,
      minAdvanceBookingHours: 2,
      bufferBetweenAppointments: 10,
      bufferType: 'after',
      allowDoubleBooking: false,
      maxConcurrentAppointments: 1,
      requireDeposit: false,
      autoAcceptBookings: true,
      acceptNewClients: true,
      displayOrder: 4,
      specialties: ['Nail Art', 'Gel Extensions', 'Dip Powder'],
    },
    notifications: {
      email: {
        appointmentReminders: true,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        dailySummary: false,
        weeklySummary: false,
        marketingEmails: false,
        systemUpdates: false,
      },
      sms: {
        appointmentReminders: true,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        urgentAlerts: true,
      },
      push: {
        appointmentReminders: true,
        newBookings: true,
        messages: true,
        teamUpdates: false,
      },
      reminderTiming: {
        firstReminder: 24,
      },
    },
    performanceGoals: {
      dailyRevenueTarget: 400,
      weeklyRevenueTarget: 2000,
    },
    isActive: true,
    createdAt: '2022-08-20T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'tm5',
    ...defaultSyncFields,
    profile: {
      id: 'tm5',
      firstName: 'David',
      lastName: 'Park',
      displayName: 'David P.',
      email: 'david@mangosalon.com',
      phone: '(555) 567-8901',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      bio: 'Salon manager with extensive experience in operations and client relations.',
      title: 'Salon Manager',
      hireDate: '2018-01-10',
    },
    services: mockServices.map((s) => ({ ...s, canPerform: false })),
    workingHours: {
      regularHours: [
        { dayOfWeek: 0, isWorking: false, shifts: [] },
        { dayOfWeek: 1, isWorking: true, shifts: [{ startTime: '08:00', endTime: '17:00' }] },
        { dayOfWeek: 2, isWorking: true, shifts: [{ startTime: '08:00', endTime: '17:00' }] },
        { dayOfWeek: 3, isWorking: true, shifts: [{ startTime: '08:00', endTime: '17:00' }] },
        { dayOfWeek: 4, isWorking: true, shifts: [{ startTime: '08:00', endTime: '17:00' }] },
        { dayOfWeek: 5, isWorking: true, shifts: [{ startTime: '08:00', endTime: '17:00' }] },
        { dayOfWeek: 6, isWorking: false, shifts: [] },
      ],
      timeOffRequests: [],
      scheduleOverrides: [],
      defaultBreakDuration: 60,
      autoScheduleBreaks: false,
    },
    permissions: {
      role: 'manager',
      permissions: defaultPermissions.map((p) => ({ ...p, level: 'full' as const })),
      canAccessAdminPortal: true,
      canAccessReports: true,
      canModifyPrices: true,
      canProcessRefunds: true,
      canDeleteRecords: true,
      canManageTeam: true,
      canViewOthersCalendar: true,
      canBookForOthers: true,
      canEditOthersAppointments: true,
      pinRequired: true,
      pin: '9999',
    },
    commission: {
      type: 'flat',
      basePercentage: 0,
      flatAmount: 500,
      productCommission: 0,
      tipHandling: 'pool',
    },
    payroll: {
      payPeriod: 'monthly',
      baseSalary: 5000,
    },
    onlineBooking: {
      isBookableOnline: false,
      showOnWebsite: false,
      showOnApp: false,
      maxAdvanceBookingDays: 0,
      minAdvanceBookingHours: 0,
      bufferBetweenAppointments: 0,
      bufferType: 'after',
      allowDoubleBooking: false,
      maxConcurrentAppointments: 0,
      requireDeposit: false,
      autoAcceptBookings: false,
      acceptNewClients: false,
      displayOrder: 99,
    },
    notifications: {
      email: {
        appointmentReminders: false,
        appointmentChanges: true,
        newBookings: true,
        cancellations: true,
        dailySummary: true,
        weeklySummary: true,
        marketingEmails: true,
        systemUpdates: true,
      },
      sms: {
        appointmentReminders: false,
        appointmentChanges: false,
        newBookings: false,
        cancellations: true,
        urgentAlerts: true,
      },
      push: {
        appointmentReminders: false,
        newBookings: true,
        messages: true,
        teamUpdates: true,
      },
      reminderTiming: {
        firstReminder: 24,
      },
    },
    performanceGoals: {},
    isActive: true,
    createdAt: '2018-01-10T00:00:00Z',
    updatedAt: '2024-01-14T00:00:00Z',
  },
];

export const permissionCategories = [
  { id: 'appointments', name: 'Appointments', icon: 'calendar' },
  { id: 'clients', name: 'Clients', icon: 'users' },
  { id: 'sales', name: 'Sales & Checkout', icon: 'credit-card' },
  { id: 'reports', name: 'Reports & Analytics', icon: 'bar-chart' },
  { id: 'team', name: 'Team Management', icon: 'user-plus' },
  { id: 'settings', name: 'System Settings', icon: 'settings' },
  { id: 'inventory', name: 'Inventory', icon: 'package' },
];
