/**
 * AddTeamMember Types
 */

import type { StaffRole } from '../../types';

export type WizardStep = 'basics' | 'schedule' | 'services' | 'review' | 'success';

export interface BasicInfo {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  role: StaffRole;
  title: string;
  bio: string;
}

export type PasswordSetupMethod = 'none' | 'manual' | 'invite';

export interface LoginCredentials {
  pin: string;
  pinAutoGenerated: boolean;
  enablePasswordLogin: boolean;
  passwordSetupMethod: PasswordSetupMethod;
  password: string;
  sendNotification: boolean;
  notificationMethod: 'email' | 'sms' | 'both';
}

export interface WizardStepConfig {
  id: WizardStep;
  label: string;
  description: string;
}
