-- ============================================================================
-- Migration: 014_create_salon_devices_table.sql
-- Description: Create salon_devices table for MQTT device discovery and presence
-- Part of: MQTT Architecture Implementation (Phase 0)
-- ============================================================================

-- Create salon_devices table
CREATE TABLE IF NOT EXISTS salon_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Store relationship
  store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,

  -- Device identification
  device_fingerprint TEXT NOT NULL,
  device_name TEXT,
  device_type TEXT NOT NULL CHECK (device_type IN ('ios', 'android', 'web', 'desktop')),

  -- MQTT configuration
  mqtt_client_id TEXT UNIQUE,
  local_ip TEXT,
  mqtt_port INTEGER DEFAULT 1883,
  is_hub BOOLEAN DEFAULT false,  -- True for Store App (runs Mosquitto broker)

  -- Presence tracking
  is_online BOOLEAN DEFAULT false,
  last_seen_at TIMESTAMPTZ DEFAULT now(),

  -- Device capabilities (JSON)
  -- Example: { "tapToPay": true, "printer": false, "scanner": true, "nfc": true }
  capabilities JSONB DEFAULT '{}',

  -- Device settings (JSON)
  -- Example: { "autoConnect": true, "preferLocalBroker": true }
  settings JSONB DEFAULT '{}',

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  -- Ensure unique device per store
  UNIQUE(store_id, device_fingerprint)
);

-- Create indexes for efficient queries
-- Index for finding hub device in a store (most common query)
CREATE INDEX idx_salon_devices_store_hub
  ON salon_devices(store_id, is_hub)
  WHERE is_hub = true;

-- Index for finding online devices
CREATE INDEX idx_salon_devices_store_online
  ON salon_devices(store_id, is_online)
  WHERE is_online = true;

-- Index for MQTT client lookup
CREATE INDEX idx_salon_devices_mqtt_client_id
  ON salon_devices(mqtt_client_id);

-- Index for last_seen cleanup queries
CREATE INDEX idx_salon_devices_last_seen
  ON salon_devices(last_seen_at);

-- Enable Row Level Security
ALTER TABLE salon_devices ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only access devices belonging to their store
CREATE POLICY "salon_devices_store_policy" ON salon_devices
  FOR ALL
  USING (
    store_id IN (
      SELECT store_id FROM store_members
      WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    store_id IN (
      SELECT store_id FROM store_members
      WHERE user_id = auth.uid()
    )
  );

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_salon_devices_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_salon_devices_updated_at
  BEFORE UPDATE ON salon_devices
  FOR EACH ROW
  EXECUTE FUNCTION update_salon_devices_updated_at();

-- Create function to mark device offline after timeout
-- This can be called by a scheduled job or Supabase Edge Function
CREATE OR REPLACE FUNCTION mark_stale_devices_offline(timeout_minutes INTEGER DEFAULT 2)
RETURNS INTEGER AS $$
DECLARE
  rows_updated INTEGER;
BEGIN
  UPDATE salon_devices
  SET is_online = false
  WHERE is_online = true
    AND last_seen_at < (now() - (timeout_minutes || ' minutes')::INTERVAL);

  GET DIAGNOSTICS rows_updated = ROW_COUNT;
  RETURN rows_updated;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission on the function
GRANT EXECUTE ON FUNCTION mark_stale_devices_offline(INTEGER) TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE salon_devices IS 'Stores device information for MQTT broker discovery and presence tracking. Each Store App acts as a hub (is_hub=true) running a local Mosquitto broker.';

COMMENT ON COLUMN salon_devices.device_fingerprint IS 'Unique device fingerprint generated by deviceManager.ts';
COMMENT ON COLUMN salon_devices.mqtt_client_id IS 'MQTT client ID in format: mango-{deviceType}-{deviceId}';
COMMENT ON COLUMN salon_devices.local_ip IS 'Local network IP address for direct MQTT connection';
COMMENT ON COLUMN salon_devices.is_hub IS 'True if this device runs the local Mosquitto broker (Store App)';
COMMENT ON COLUMN salon_devices.capabilities IS 'JSON object describing device capabilities like tapToPay, printer, scanner';
