/**
 * Menu Settings Constants
 * Default values, colors, icons, and configuration.
 *
 * Note: Sample data (sampleCategories, sampleServices, etc.) is deprecated.
 * Use catalogSeed.ts for seeding the database with sample data.
 */

import type { MenuGeneralSettings } from './types';

// Category Color Palette (Fresha-inspired)
export const CATEGORY_COLORS = [
  { name: 'Rose', value: '#F43F5E', bg: 'bg-rose-500', light: 'bg-rose-50', text: 'text-rose-600' },
  { name: 'Pink', value: '#EC4899', bg: 'bg-pink-500', light: 'bg-pink-50', text: 'text-pink-600' },
  { name: 'Fuchsia', value: '#D946EF', bg: 'bg-fuchsia-500', light: 'bg-fuchsia-50', text: 'text-fuchsia-600' },
  { name: 'Purple', value: '#A855F7', bg: 'bg-purple-500', light: 'bg-purple-50', text: 'text-purple-600' },
  { name: 'Violet', value: '#8B5CF6', bg: 'bg-violet-500', light: 'bg-violet-50', text: 'text-violet-600' },
  { name: 'Indigo', value: '#6366F1', bg: 'bg-indigo-500', light: 'bg-indigo-50', text: 'text-indigo-600' },
  { name: 'Blue', value: '#3B82F6', bg: 'bg-blue-500', light: 'bg-blue-50', text: 'text-blue-600' },
  { name: 'Cyan', value: '#06B6D4', bg: 'bg-cyan-500', light: 'bg-cyan-50', text: 'text-cyan-600' },
  { name: 'Teal', value: '#14B8A6', bg: 'bg-teal-500', light: 'bg-teal-50', text: 'text-teal-600' },
  { name: 'Emerald', value: '#10B981', bg: 'bg-emerald-500', light: 'bg-emerald-50', text: 'text-emerald-600' },
  { name: 'Green', value: '#22C55E', bg: 'bg-green-500', light: 'bg-green-50', text: 'text-green-600' },
  { name: 'Lime', value: '#84CC16', bg: 'bg-lime-500', light: 'bg-lime-50', text: 'text-lime-600' },
  { name: 'Yellow', value: '#EAB308', bg: 'bg-yellow-500', light: 'bg-yellow-50', text: 'text-yellow-600' },
  { name: 'Amber', value: '#F59E0B', bg: 'bg-amber-500', light: 'bg-amber-50', text: 'text-amber-600' },
  { name: 'Orange', value: '#F97316', bg: 'bg-orange-500', light: 'bg-orange-50', text: 'text-orange-600' },
  { name: 'Red', value: '#EF4444', bg: 'bg-red-500', light: 'bg-red-50', text: 'text-red-600' },
];

// Category Icons
export const CATEGORY_ICONS = [
  'Scissors', 'Paintbrush', 'Sparkles', 'Heart', 'Star', 'Gem',
  'Flower2', 'Leaf', 'Sun', 'Moon', 'Droplet', 'Flame',
  'Wind', 'Waves', 'CloudSun', 'Rainbow', 'Palette', 'Crown'
];

// Duration Options (in minutes)
export const DURATION_OPTIONS = [
  { value: 15, label: '15 min' },
  { value: 30, label: '30 min' },
  { value: 45, label: '45 min' },
  { value: 60, label: '1 hour' },
  { value: 75, label: '1h 15min' },
  { value: 90, label: '1h 30min' },
  { value: 105, label: '1h 45min' },
  { value: 120, label: '2 hours' },
  { value: 150, label: '2h 30min' },
  { value: 180, label: '3 hours' },
  { value: 240, label: '4 hours' },
  { value: 300, label: '5 hours' },
  { value: 360, label: '6 hours' },
];

// Processing/Buffer Time Options
export const PROCESSING_TIME_OPTIONS = [
  { value: 0, label: 'No buffer' },
  { value: 5, label: '5 min' },
  { value: 10, label: '10 min' },
  { value: 15, label: '15 min' },
  { value: 20, label: '20 min' },
  { value: 30, label: '30 min' },
  { value: 45, label: '45 min' },
  { value: 60, label: '1 hour' },
];

// Default Menu Settings
export const defaultMenuSettings: MenuGeneralSettings = {
  defaultDuration: 60,
  defaultProcessingTime: 0,
  showPricesOnline: true,
  requireDepositForOnlineBooking: false,
  defaultDepositPercentage: 20,
  taxRate: 0,
  currency: 'USD',
  currencySymbol: '$',
  allowCustomPricing: true,
  enablePackages: true,
  enableAddOns: true,
};

/**
 * @deprecated Use catalogSeed.ts for sample data.
 * These sample data arrays are kept only for backward compatibility.
 */
export const sampleCategories: any[] = [
  {
    id: 'cat-1',
    name: 'Hair Services',
    description: 'Haircuts, styling, and treatments',
    color: '#F43F5E',
    icon: 'Scissors',
    displayOrder: 1,
    isActive: true,
    servicesCount: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-2',
    name: 'Hair Color',
    description: 'Coloring, highlights, and balayage',
    color: '#A855F7',
    icon: 'Paintbrush',
    displayOrder: 2,
    isActive: true,
    servicesCount: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-3',
    name: 'Nail Services',
    description: 'Manicures, pedicures, and nail art',
    color: '#EC4899',
    icon: 'Sparkles',
    displayOrder: 3,
    isActive: true,
    servicesCount: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-4',
    name: 'Spa & Massage',
    description: 'Relaxation and therapeutic treatments',
    color: '#14B8A6',
    icon: 'Leaf',
    displayOrder: 4,
    isActive: true,
    servicesCount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-5',
    name: 'Facial & Skincare',
    description: 'Facials, peels, and skin treatments',
    color: '#06B6D4',
    icon: 'Droplet',
    displayOrder: 5,
    isActive: true,
    servicesCount: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-6',
    name: 'Waxing',
    description: 'Body and facial waxing services',
    color: '#F59E0B',
    icon: 'Flame',
    displayOrder: 6,
    isActive: true,
    servicesCount: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-7',
    name: 'Makeup',
    description: 'Professional makeup services',
    color: '#8B5CF6',
    icon: 'Palette',
    displayOrder: 7,
    isActive: true,
    servicesCount: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-8',
    name: 'Lashes & Brows',
    description: 'Eyelash extensions and brow services',
    color: '#6366F1',
    icon: 'Star',
    displayOrder: 8,
    isActive: true,
    servicesCount: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Sample Services for Demo
/** @deprecated Use catalogSeed.ts */
export const sampleServices: any[] = [
  // Hair Services
  {
    id: 'svc-1',
    categoryId: 'cat-1',
    name: "Women's Haircut",
    description: 'Consultation, shampoo, cut, and style',
    pricingType: 'from',
    price: 65,
    duration: 60,
    processingTime: 0,
    hasVariants: true,
    variants: [
      { id: 'v1', name: 'Short Hair', duration: 45, price: 65, isDefault: true },
      { id: 'v2', name: 'Medium Hair', duration: 60, price: 75 },
      { id: 'v3', name: 'Long Hair', duration: 75, price: 85 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 1,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-2',
    categoryId: 'cat-1',
    name: "Men's Haircut",
    description: 'Classic cut with neck cleanup',
    pricingType: 'fixed',
    price: 35,
    duration: 30,
    processingTime: 0,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 2,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-3',
    categoryId: 'cat-1',
    name: 'Blowout & Style',
    description: 'Shampoo and professional blowdry styling',
    pricingType: 'from',
    price: 45,
    duration: 45,
    hasVariants: true,
    variants: [
      { id: 'v1', name: 'Short/Medium', duration: 45, price: 45, isDefault: true },
      { id: 'v2', name: 'Long Hair', duration: 60, price: 55 },
      { id: 'v3', name: 'Extra Long', duration: 75, price: 65 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 3,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-4',
    categoryId: 'cat-1',
    name: 'Deep Conditioning Treatment',
    description: 'Intensive hydration and repair treatment',
    pricingType: 'fixed',
    price: 35,
    duration: 30,
    processingTime: 15,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 4,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Hair Color
  {
    id: 'svc-5',
    categoryId: 'cat-2',
    name: 'Full Color',
    description: 'Single process all-over color',
    pricingType: 'from',
    price: 95,
    duration: 90,
    processingTime: 30,
    hasVariants: true,
    variants: [
      { id: 'v1', name: 'Short Hair', duration: 90, price: 95, isDefault: true },
      { id: 'v2', name: 'Medium Hair', duration: 105, price: 115 },
      { id: 'v3', name: 'Long Hair', duration: 120, price: 135 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: true,
    depositPercentage: 25,
    taxable: true,
    status: 'active',
    displayOrder: 1,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-6',
    categoryId: 'cat-2',
    name: 'Balayage',
    description: 'Hand-painted highlights for natural dimension',
    pricingType: 'from',
    price: 175,
    duration: 180,
    processingTime: 30,
    hasVariants: true,
    variants: [
      { id: 'v1', name: 'Partial Balayage', duration: 150, price: 175, isDefault: true },
      { id: 'v2', name: 'Full Balayage', duration: 180, price: 225 },
      { id: 'v3', name: 'Full + Root Shadow', duration: 210, price: 275 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: true,
    depositPercentage: 30,
    taxable: true,
    status: 'active',
    displayOrder: 2,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nail Services
  {
    id: 'svc-7',
    categoryId: 'cat-3',
    name: 'Classic Manicure',
    description: 'Nail shaping, cuticle care, and polish',
    pricingType: 'fixed',
    price: 28,
    duration: 30,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 1,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-8',
    categoryId: 'cat-3',
    name: 'Gel Manicure',
    description: 'Long-lasting gel polish manicure',
    pricingType: 'fixed',
    price: 45,
    duration: 45,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 2,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-9',
    categoryId: 'cat-3',
    name: 'Deluxe Pedicure',
    description: 'Full pedicure with extended massage and mask',
    pricingType: 'fixed',
    price: 55,
    duration: 60,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: true,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 3,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Spa & Massage
  {
    id: 'svc-10',
    categoryId: 'cat-4',
    name: 'Swedish Massage',
    description: 'Classic relaxation massage',
    pricingType: 'from',
    price: 85,
    duration: 60,
    hasVariants: true,
    variants: [
      { id: 'v1', name: '60 Minutes', duration: 60, price: 85, isDefault: true },
      { id: 'v2', name: '90 Minutes', duration: 90, price: 125 },
      { id: 'v3', name: '120 Minutes', duration: 120, price: 165 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: true,
    depositPercentage: 20,
    taxable: true,
    status: 'active',
    displayOrder: 1,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-11',
    categoryId: 'cat-4',
    name: 'Deep Tissue Massage',
    description: 'Therapeutic pressure for muscle relief',
    pricingType: 'from',
    price: 95,
    duration: 60,
    hasVariants: true,
    variants: [
      { id: 'v1', name: '60 Minutes', duration: 60, price: 95, isDefault: true },
      { id: 'v2', name: '90 Minutes', duration: 90, price: 140 },
    ],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: true,
    depositPercentage: 20,
    taxable: true,
    status: 'active',
    displayOrder: 2,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Facial & Skincare
  {
    id: 'svc-12',
    categoryId: 'cat-5',
    name: 'Express Facial',
    description: 'Quick refresh facial treatment',
    pricingType: 'fixed',
    price: 65,
    duration: 30,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: false,
    taxable: true,
    status: 'active',
    displayOrder: 1,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'svc-13',
    categoryId: 'cat-5',
    name: 'Signature Facial',
    description: 'Full customized facial with extractions',
    pricingType: 'fixed',
    price: 125,
    duration: 75,
    hasVariants: false,
    variants: [],
    assignedStaffIds: [],
    allStaffCanPerform: false,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    requiresDeposit: true,
    depositPercentage: 20,
    taxable: true,
    status: 'active',
    displayOrder: 2,
    showPriceOnline: true,
    allowCustomDuration: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Sample Packages
/** @deprecated Use catalogSeed.ts */
export const samplePackages: any[] = [
  {
    id: 'pkg-1',
    name: 'Bridal Beauty Package',
    description: 'Complete bridal preparation including hair, makeup, and nails',
    services: [
      { serviceId: 'svc-1', serviceName: "Women's Haircut", quantity: 1, originalPrice: 75 },
      { serviceId: 'svc-3', serviceName: 'Blowout & Style', quantity: 1, originalPrice: 55 },
      { serviceId: 'svc-8', serviceName: 'Gel Manicure', quantity: 1, originalPrice: 45 },
    ],
    originalPrice: 175,
    packagePrice: 149,
    discountType: 'fixed',
    discountValue: 26,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    isActive: true,
    displayOrder: 1,
    color: '#EC4899',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'pkg-2',
    name: 'Spa Day Escape',
    description: 'Ultimate relaxation with massage and facial',
    services: [
      { serviceId: 'svc-10', serviceName: 'Swedish Massage', quantity: 1, originalPrice: 125 },
      { serviceId: 'svc-13', serviceName: 'Signature Facial', quantity: 1, originalPrice: 125 },
    ],
    originalPrice: 250,
    packagePrice: 215,
    discountType: 'percentage',
    discountValue: 14,
    validityDays: 90,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    isActive: true,
    displayOrder: 2,
    color: '#14B8A6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'pkg-3',
    name: 'Color & Care Package',
    description: 'Full color service with deep conditioning treatment',
    services: [
      { serviceId: 'svc-5', serviceName: 'Full Color', quantity: 1, originalPrice: 115 },
      { serviceId: 'svc-4', serviceName: 'Deep Conditioning Treatment', quantity: 1, originalPrice: 35 },
      { serviceId: 'svc-3', serviceName: 'Blowout & Style', quantity: 1, originalPrice: 55 },
    ],
    originalPrice: 205,
    packagePrice: 179,
    discountType: 'fixed',
    discountValue: 26,
    bookingAvailability: 'both',
    onlineBookingEnabled: true,
    isActive: true,
    displayOrder: 3,
    color: '#A855F7',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Sample Add-ons
/** @deprecated Use catalogSeed.ts */
export const sampleAddOns: any[] = [
  {
    id: 'addon-1',
    name: 'Scalp Massage',
    description: 'Relaxing scalp massage add-on',
    price: 15,
    duration: 10,
    applicableToAll: false,
    applicableCategoryIds: ['cat-1', 'cat-2'],
    applicableServiceIds: [],
    isActive: true,
    displayOrder: 1,
    onlineBookingEnabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'addon-2',
    name: 'Paraffin Treatment',
    description: 'Moisturizing paraffin wax treatment',
    price: 12,
    duration: 10,
    applicableToAll: false,
    applicableCategoryIds: ['cat-3'],
    applicableServiceIds: [],
    isActive: true,
    displayOrder: 2,
    onlineBookingEnabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'addon-3',
    name: 'Hot Stone Enhancement',
    description: 'Add hot stones to your massage',
    price: 25,
    duration: 15,
    applicableToAll: false,
    applicableCategoryIds: ['cat-4'],
    applicableServiceIds: [],
    isActive: true,
    displayOrder: 3,
    onlineBookingEnabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'addon-4',
    name: 'Nail Art (per nail)',
    description: 'Custom nail art design',
    price: 5,
    duration: 5,
    applicableToAll: false,
    applicableCategoryIds: ['cat-3'],
    applicableServiceIds: [],
    isActive: true,
    displayOrder: 4,
    onlineBookingEnabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'addon-5',
    name: 'Gloss Treatment',
    description: 'High-shine gloss treatment for color services',
    price: 35,
    duration: 15,
    applicableToAll: false,
    applicableCategoryIds: ['cat-2'],
    applicableServiceIds: [],
    isActive: true,
    displayOrder: 5,
    onlineBookingEnabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Helper function to format duration
export const formatDuration = (minutes: number): string => {
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}min`;
};

// Helper function to format price
export const formatPrice = (price: number, currencySymbol: string = '$'): string => {
  return `${currencySymbol}${price.toFixed(0)}`;
};

// Helper function to get color class from hex
export const getColorClasses = (hexColor: string) => {
  const colorObj = CATEGORY_COLORS.find(c => c.value === hexColor);
  return colorObj || { bg: 'bg-gray-500', light: 'bg-gray-50', text: 'text-gray-600' };
};
